// Code generated by internal/tools/gen/providerdocs from the provider registry; DO NOT EDIT.

package main

// providerNames are short names for the menu bar.
var providerNames = map[string]string{
	"alibaba":     "Alibaba Cloud",
	"anthropic":   "Claude",
	"atlascloud":  "Atlas Cloud",
	"bifrost":     "Bifrost",
	"cerebras":    "Cerebras",
	"chutes":      "Chutes",
	"clawrouter":  "ClawRouter",
	"cursor":      "Cursor",
	"deepgram":    "Deepgram",
	"deepinfra":   "DeepInfra",
	"deepseek":    "DeepSeek",
	"fireworks":   "Fireworks",
	"gemini":      "Gemini",
	"github":      "Copilot",
	"kimi":        "Kimi",
	"litellm":     "LiteLLM",
	"minimax":     "MiniMax",
	"mistral":     "Mistral",
	"moonshot":    "Moonshot",
	"neuralwatt":  "Neuralwatt",
	"openai":      "Codex",
	"opencode":    "opencode",
	"opencode-go": "opencode Go",
	"openrouter":  "OpenRouter",
	"poe":         "Poe",
	"synthetic":   "Synthetic",
	"together":    "Together AI",
	"vercel":      "Vercel",
	"xai":         "xAI",
	"zai":         "z.ai",
	"zhipuai":     "Zhipu AI",
}
