package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"go.klarlabs.de/tokenops/internal/version"
)

// opencode is the only client besides Claude Code where read-guard can
// actually refuse a read. Codex has no file-read tool at all, and
// Cursor's beforeReadFile is observe-only — both are recorded as
// permanently unavailable in the capability matrix. opencode has a `read`
// tool and a `tool.execute.before` hook that blocks when it throws.
//
// What it does not have is a config file we can merge into: its
// extension point is a JavaScript module. So this generates one.
//
// Generating rather than shipping is the whole design. A published
// package would mean a second artifact, a second release path, and a
// version skew between the plugin and the binary it calls. A generated
// file has none of that: it is written by the binary, names the version
// that wrote it, hardcodes the absolute path to that same binary, and is
// rewritten in place by the next `hooks install`. It is a config file
// that happens to be syntactically JavaScript, which is what the other
// three clients get too — theirs just happen to be JSON.

// opencodePluginName is the generated file. Named for tokenops so a
// human reading their plugin directory knows what wrote it and what to
// delete.
const opencodePluginName = "tokenops-read-guard.ts"

// opencodePluginTemplate is the shim. %s is the absolute path to this
// binary.
//
// Three properties it must have, in order of how badly each would hurt:
//
//   - It FAILS OPEN. A guard sitting in front of every file read must
//     never be the reason an agent cannot read a file. Anything
//     unexpected — the binary missing, a spawn failure, unparseable
//     output — allows the read. Only an explicit deny throws, and the
//     throw happens outside the try so a bug in the error handling
//     cannot swallow a real refusal.
//   - It omits offset and limit rather than sending null. read-guard
//     treats the mere presence of either as a ranged read and always
//     allows those, so a literal null would disable the guard entirely
//     while appearing to work.
//   - It says nothing on allow. read-guard exits 0 with empty stdout for
//     a read it permits, which is the common case and must stay silent.
const opencodePluginTemplate = `// Generated by tokenops %s — do not edit.
//
// Regenerate with:
//   tokenops hooks install --read-guard --coach --client opencode
//
// Delete this file to remove it. Decisions are made by the tokenops
// binary below, which follows coaching.delivery in your tokenops config.
const TOKENOPS = %q

// run pipes a payload to the tokenops binary and returns its stdout,
// or null if anything at all went wrong. Everything here fails open:
// a coaching tool must never be the reason an agent cannot work.
async function run(args, payload) {
  try {
    const proc = Bun.spawn([TOKENOPS, ...args], {
      stdin: new TextEncoder().encode(JSON.stringify(payload)),
      stdout: "pipe",
      stderr: "ignore",
    })
    const out = (await new Response(proc.stdout).text()).trim()
    return out || null
  } catch {
    return null
  }
}

export const Tokenops = async ({ client }) => ({
%s%s})
`

// opencodeHookBody is the read-guard half: refuse a redundant full
// re-read of an unchanged file.
//
// Two properties it must have. The deny is decided inside the try and
// thrown OUTSIDE it, so a bug in the error handling cannot swallow a real
// refusal and nothing else can escape. And offset/limit are OMITTED when
// absent rather than sent as null — read-guard treats the presence of
// either as a ranged read and always allows those, so a literal null
// would disable the guard entirely while appearing to work.
func opencodeHookBody(on bool) string {
	if !on {
		return ""
	}
	return `  "tool.execute.before": async (input, output) => {
    if (input?.tool !== "read") return
    const filePath = output?.args?.filePath
    if (!filePath) return
    let denyReason = null
    try {
      const toolInput = { file_path: filePath }
      if (output.args.offset !== undefined && output.args.offset !== null) {
        toolInput.offset = output.args.offset
      }
      if (output.args.limit !== undefined && output.args.limit !== null) {
        toolInput.limit = output.args.limit
      }
      const out = await run(["read-guard"], {
        session_id: input.sessionID ?? "",
        tool_name: "Read",
        tool_input: toolInput,
      })
      if (out) {
        const d = JSON.parse(out)?.hookSpecificOutput
        if (d?.permissionDecision === "deny") {
          denyReason = d.permissionDecisionReason || "tokenops read-guard: redundant re-read"
        }
      }
    } catch {
      // fail open
    }
    if (denyReason) throw new Error(denyReason)
  },
`
}

// opencodeIdleBody is the coaching half. opencode has no end-of-turn
// hook that takes a return value, so the nudge is delivered as a TUI
// toast — the one channel a plugin has to reach the operator.
//
// It carries no tokens in the event and no transcript path: the turns
// live in opencode's own store, which the binary reads by session id.
func opencodeIdleBody(on bool, budget float64) string {
	if !on {
		return ""
	}
	// The budget is baked in like the other clients' installers do, so
	// `--budget` is not silently ignored here alone.
	return `  event: async ({ event }) => {
    if (event?.type !== "session.idle") return
    const sessionID = event?.properties?.sessionID ?? event?.properties?.info?.id
    if (!sessionID) return
    try {
      const out = await run(["coach-hook", "--budget", "` + formatBudget(budget) + `"], {
        session_id: sessionID,
        hook_event_name: "session.idle",
      })
      if (!out) return
      const msg = JSON.parse(out)?.systemMessage
      if (msg) {
        await client.tui.showToast({ body: { title: "tokenops", message: msg, variant: "warning" } })
      }
    } catch {
      // fail open: a nudge that cannot be delivered is not worth an error
    }
  },
`
}

// opencodeRouteBody is the per-turn model-fit half.
//
// chat.message is opencode's prompt hook, and its input is better than
// any other client's for this: it names the provider and the model
// outright, where Claude Code makes the model a search through the
// transcript. The advice is appended to the message parts, which is the
// only channel a plugin has into the turn the operator just opened.
func opencodeRouteBody(on bool) string {
	if !on {
		return ""
	}
	return `  "chat.message": async (input, output) => {
    try {
      const text = (output?.parts ?? [])
        .filter((p) => p?.type === "text")
        .map((p) => p.text)
        .join(" ")
      if (!text.trim()) return
      const out = await run(["route-guard"], {
        session_id: input?.sessionID ?? "",
        prompt: text,
        provider_id: input?.model?.providerID ?? "",
        model_id: input?.model?.modelID ?? "",
      })
      if (!out) return
      const advice = JSON.parse(out)?.hookSpecificOutput?.additionalContext
      if (advice) {
        output.parts.push({ type: "text", text: advice })
      }
    } catch {
      // fail open: a turn must never fail because the guard could not decide
    }
  },
`
}

// installOpencodePlugin writes the generated shim.
func installOpencodePlugin(out io.Writer, dir, exe string, readGuard, coach, routeGuard, dryRun bool, budget float64) error {
	if !readGuard && !coach && !routeGuard {
		return fmt.Errorf("nothing selected: pass --read-guard, --coach, --route-guard, or a combination")
	}
	path := filepath.Join(dir, opencodePluginName)
	body := fmt.Sprintf(opencodePluginTemplate, version.String(), exe,
		opencodeHookBody(readGuard), opencodeIdleBody(coach, budget)+opencodeRouteBody(routeGuard))

	if existing, err := os.ReadFile(path); err == nil && string(existing) == body {
		fmt.Fprintln(out, "Already up to date — no changes.")
		return nil
	}
	if readGuard {
		fmt.Fprintf(out, "  + read-guard (opencode tool.execute.before) -> %s\n", opencodePluginName)
	}
	if coach {
		fmt.Fprintf(out, "  + coach-hook (opencode session.idle) -> %s\n", opencodePluginName)
	}
	if routeGuard {
		fmt.Fprintf(out, "  + route-guard (opencode chat.message) -> %s\n", opencodePluginName)
	}
	if dryRun {
		fmt.Fprintln(out, "\n--dry-run: not writing. Resulting plugin:")
		fmt.Fprintln(out, body)
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil { //nolint:gosec // a plugin the operator asked for
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Fprintf(out, "Wrote %s\n", path)
	fmt.Fprintln(out, "\nRestart opencode to load it. It refuses a read only at")
	fmt.Fprintln(out, "`coaching.delivery: intervene`; below that it records and allows.")
	return nil
}

// opencodePluginDir is where opencode loads global plugins from.
func opencodePluginDir(override string) (string, error) {
	if override != "" {
		return override, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home for ~/.config/opencode/plugins: %w", err)
	}
	return filepath.Join(home, ".config", "opencode", "plugins"), nil
}

// opencodeClient reports whether the flag names opencode.
func opencodeClient(client string) bool {
	return strings.EqualFold(client, hookClientOpencode)
}
