package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.klarlabs.de/tokenops/internal/infra/opencodeplugin"
)

// An install replaces the separate opencode 2 file an older tokenops
// wrote: both carry the id "tokenops", and opencode 2 would load it as a
// second plugin.
func TestInstallOpencodeReplacesTheLegacyV2File(t *testing.T) {
	dir := t.TempDir()
	legacy := filepath.Join(dir, opencodeplugin.LegacyV2FileName)
	if err := os.WriteFile(legacy, []byte("// Generated by tokenops v0.90.0 for opencode 2 — do not edit.\nconst TOKENOPS = \"/bin/tokenops\"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if err := installOpencodePlugin(&out, dir, "/bin/tokenops", true, false, false, false, 50); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(legacy); !os.IsNotExist(err) {
		t.Errorf("legacy opencode 2 plugin left behind:\n%s", out.String())
	}
	b, err := os.ReadFile(filepath.Join(dir, opencodePluginName))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "async setup(ctx)") || !strings.Contains(string(b), "server: async") {
		t.Errorf("the one plugin must serve both versions:\n%s", b)
	}
}

// A file the operator wrote under the legacy name is theirs, not ours.
func TestInstallOpencodeLeavesAForeignV2FileAlone(t *testing.T) {
	dir := t.TempDir()
	foreign := filepath.Join(dir, opencodeplugin.LegacyV2FileName)
	if err := os.WriteFile(foreign, []byte("export default { id: \"mine\" }\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if err := installOpencodePlugin(&out, dir, "/bin/tokenops", true, false, false, false, 50); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(foreign); err != nil {
		t.Errorf("a plugin tokenops did not write was removed: %v", err)
	}
}
