package cli

import (
	"context"
	"os/exec"
	"strings"
	"time"
)

// opencode 2 does not run 1.x plugins. A 2.x plugin default-exports
// Plugin.define({id, setup}) and registers its hooks on the context in
// setup; 1.x returns a hooks object from a named export. Both versions
// read plugin files from ~/.config/opencode/plugins, and each skips the
// other's file with a logged load error, so during a transition both
// files can sit side by side. Verified on opencode 2.0.22 and 1.18.32.

// opencodeV2PluginName is the generated 2.x plugin.
const opencodeV2PluginName = "tokenops-v2.js"

// opencodeV2PluginTemplate is the 2.x shim; see opencodePluginTemplate for
// the properties both must have. The first %s is the version, %q the
// binary, the last %s the hook registrations.
const opencodeV2PluginTemplate = `// Generated by tokenops %s for opencode 2 — do not edit.
//
// Regenerate with:
//   tokenops hooks install --read-guard --route-guard --client opencode
//
// Delete this file to remove it. Decisions are made by the tokenops
// binary below, which follows the coach settings in your tokenops config.
const TOKENOPS = %q

// run pipes a payload to the tokenops binary and returns its stdout,
// or null if anything at all went wrong. Everything here fails open:
// a coaching tool must never be the reason an agent cannot work.
async function run(args, payload) {
  try {
    const proc = Bun.spawn([TOKENOPS, ...args], {
      stdin: new TextEncoder().encode(JSON.stringify(payload)),
      stdout: "pipe",
      stderr: "ignore",
    })
    const out = (await new Response(proc.stdout).text()).trim()
    return out || null
  } catch {
    return null
  }
}

export default {
  id: "tokenops",
  async setup(ctx) {
%s  },
}
`

// opencodeV2ReadGuardBody refuses a redundant full re-read. opencode 2
// names the file "path" (a 1.x call migrated to 2.x keeps "filePath"),
// and refusing is a throw from tool.execute.before, as in 1.x. A read
// from the start (offset 0 or 1) with no limit is a full read; any limit
// or later offset is a ranged read, which read-guard always allows.
func opencodeV2ReadGuardBody(on bool) string {
	if !on {
		return ""
	}
	return `    await ctx.tool.hook("execute.before", async (event) => {
      if (event?.tool !== "read") return
      const args = event.input ?? {}
      const filePath = args.path ?? args.filePath
      if (!filePath) return
      let denyReason = null
      try {
        const toolInput = { file_path: filePath }
        if (typeof args.offset === "number" && args.offset > 1) toolInput.offset = args.offset
        if (args.limit !== undefined && args.limit !== null) toolInput.limit = args.limit
        const out = await run(["read-guard"], {
          session_id: event.sessionID ?? "",
          tool_name: "Read",
          tool_input: toolInput,
        })
        if (out) {
          const d = JSON.parse(out)?.hookSpecificOutput
          if (d?.permissionDecision === "deny") {
            denyReason = d.permissionDecisionReason || "tokenops read-guard: redundant re-read"
          }
        }
      } catch {
        // fail open
      }
      if (denyReason) throw new Error(denyReason)
    })
`
}

// opencodeV2RouteBody checks the model still fits the work. The 2.x
// prompt hook carries the text but not the model, so the session is
// looked up for it; the advice is appended to the prompt the operator
// just submitted, the 2.x counterpart of 1.x's appended part.
func opencodeV2RouteBody(on bool) string {
	if !on {
		return ""
	}
	return `    await ctx.session.hook("prompt", async (event) => {
      try {
        const text = event?.prompt?.text ?? ""
        if (!text.trim()) return
        let model = {}
        try {
          const session = await ctx.session.get({ sessionID: event.sessionID })
          model = session?.model ?? {}
        } catch {
          // no model: route-guard still reads the work
        }
        const out = await run(["route-guard"], {
          session_id: event.sessionID ?? "",
          prompt: text,
          provider_id: model.providerID ?? "",
          model_id: model.id ?? "",
        })
        if (!out) return
        const advice = JSON.parse(out)?.hookSpecificOutput?.additionalContext
        if (advice) event.prompt.text = text + "\n\n" + advice
      } catch {
        // fail open: a turn must never fail because the guard could not decide
      }
    })
`
}

// opencodeV2Markers names the 2.x extension point each verb hooks.
var opencodeV2Markers = map[string]string{
	"read-guard":  "tool.execute.before",
	"route-guard": "session prompt",
}

// opencodeVersions reports which opencode generations are installed: 2.x
// when `opencode2` is on PATH or `opencode --version` says 2, 1.x when
// `opencode --version` says 1. With neither found it reports 1.x, the
// plugin TokenOps has always written. A variable so tests can stub it.
var opencodeVersions = func() (v1, v2 bool) {
	if _, err := exec.LookPath("opencode2"); err == nil {
		v2 = true
	}
	if path, err := exec.LookPath("opencode"); err == nil {
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		out, err := exec.CommandContext(ctx, path, "--version").Output() //nolint:gosec // the opencode binary on PATH
		if err == nil {
			version := strings.TrimPrefix(strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(string(out)), "opencode")), "v")
			switch {
			case strings.HasPrefix(version, "1."):
				v1 = true
			case strings.HasPrefix(version, "2."):
				v2 = true
			}
		}
	}
	if !v1 && !v2 {
		v1 = true
	}
	return v1, v2
}
