package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"go.klarlabs.de/tokenops/internal/version"
)

// opencode is the only client besides Claude Code where read-guard can
// actually refuse a read. Codex has no file-read tool at all, and
// Cursor's beforeReadFile is observe-only — both are recorded as
// permanently unavailable in the capability matrix. opencode has a `read`
// tool and a `tool.execute.before` hook that blocks when it throws.
//
// What it does not have is a config file we can merge into: its
// extension point is a JavaScript module. So this generates one.
//
// Generating rather than shipping is the whole design. A published
// package would mean a second artifact, a second release path, and a
// version skew between the plugin and the binary it calls. A generated
// file has none of that: it is written by the binary, names the version
// that wrote it, hardcodes the absolute path to that same binary, and is
// rewritten in place by the next `hooks install`. It is a config file
// that happens to be syntactically JavaScript, which is what the other
// three clients get too — theirs just happen to be JSON.

// opencodePluginName is the generated file. Named for tokenops so a
// human reading their plugin directory knows what wrote it and what to
// delete.
const opencodePluginName = "tokenops-read-guard.ts"

// opencodePluginTemplate is the shim. %s is the absolute path to this
// binary.
//
// Three properties it must have, in order of how badly each would hurt:
//
//   - It FAILS OPEN. A guard sitting in front of every file read must
//     never be the reason an agent cannot read a file. Anything
//     unexpected — the binary missing, a spawn failure, unparseable
//     output — allows the read. Only an explicit deny throws, and the
//     throw happens outside the try so a bug in the error handling
//     cannot swallow a real refusal.
//   - It omits offset and limit rather than sending null. read-guard
//     treats the mere presence of either as a ranged read and always
//     allows those, so a literal null would disable the guard entirely
//     while appearing to work.
//   - It says nothing on allow. read-guard exits 0 with empty stdout for
//     a read it permits, which is the common case and must stay silent.
const opencodePluginTemplate = `// Generated by tokenops %s — do not edit.
//
// Refuses a redundant full re-read of an unchanged file, which is the
// largest reclaimable slice of an agent's context. Regenerate with:
//
//   tokenops hooks install --read-guard --client opencode
//
// Delete this file to remove it. The decision is made by the tokenops
// binary below, which follows coaching.delivery in your tokenops config:
// "intervene" refuses, anything else only records what it would have
// refused.
const TOKENOPS = %q

export const TokenopsReadGuard = async () => ({
  "tool.execute.before": async (input, output) => {
    if (input?.tool !== "read") return
    const filePath = output?.args?.filePath
    if (!filePath) return

    // Decided inside the try, thrown outside it: a failure anywhere in
    // here must allow the read, and only an explicit deny must block it.
    let denyReason = null
    try {
      const toolInput = { file_path: filePath }
      // Presence alone marks a ranged read for read-guard, which always
      // allows those — so these are omitted, never sent as null.
      if (output.args.offset !== undefined && output.args.offset !== null) {
        toolInput.offset = output.args.offset
      }
      if (output.args.limit !== undefined && output.args.limit !== null) {
        toolInput.limit = output.args.limit
      }
      const payload = JSON.stringify({
        session_id: input.sessionID ?? "",
        tool_name: "Read",
        tool_input: toolInput,
      })
      const proc = Bun.spawn([TOKENOPS, "read-guard"], {
        stdin: new TextEncoder().encode(payload),
        stdout: "pipe",
        stderr: "ignore",
      })
      const out = (await new Response(proc.stdout).text()).trim()
      // Empty stdout is an allow. Only a deny says anything.
      if (out) {
        const decision = JSON.parse(out)?.hookSpecificOutput
        if (decision?.permissionDecision === "deny") {
          denyReason = decision.permissionDecisionReason || "tokenops read-guard: redundant re-read"
        }
      }
    } catch {
      // Fail open: never be the reason a read cannot happen.
    }
    if (denyReason) throw new Error(denyReason)
  },
})
`

// installOpencodePlugin writes the generated read-guard shim.
func installOpencodePlugin(out io.Writer, dir, exe string, readGuard, dryRun bool) error {
	if !readGuard {
		return fmt.Errorf(
			"opencode supports --read-guard only: its plugin API can refuse a tool call, " +
				"but tokenops cannot yet read opencode's per-turn token counts, which the " +
				"coaching nudge needs to measure a budget. Use --read-guard for opencode")
	}
	path := filepath.Join(dir, opencodePluginName)
	body := fmt.Sprintf(opencodePluginTemplate, version.String(), exe)

	if existing, err := os.ReadFile(path); err == nil && string(existing) == body {
		fmt.Fprintln(out, "Already up to date — no changes.")
		return nil
	}
	fmt.Fprintf(out, "  + read-guard (opencode tool.execute.before) -> %s\n", opencodePluginName)
	if dryRun {
		fmt.Fprintln(out, "\n--dry-run: not writing. Resulting plugin:")
		fmt.Fprintln(out, body)
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil { //nolint:gosec // a plugin the operator asked for
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Fprintf(out, "Wrote %s\n", path)
	fmt.Fprintln(out, "\nRestart opencode to load it. It refuses a read only at")
	fmt.Fprintln(out, "`coaching.delivery: intervene`; below that it records and allows.")
	return nil
}

// opencodePluginDir is where opencode loads global plugins from.
func opencodePluginDir(override string) (string, error) {
	if override != "" {
		return override, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home for ~/.config/opencode/plugins: %w", err)
	}
	return filepath.Join(home, ".config", "opencode", "plugins"), nil
}

// opencodeClient reports whether the flag names opencode.
func opencodeClient(client string) bool {
	return strings.EqualFold(client, hookClientOpencode)
}
