// TokenOps event schema, version 1.
//
// This .proto is the canonical source for cross-language consumers. Go types
// in pkg/eventschema mirror these messages and are kept hand-written so the
// public Go API can evolve independently of the Protobuf compilation step.
// Generators (.pb.go, OTel exporters, gRPC services) live under tooling that
// will be added in subsequent tasks; this file is the contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: pkg/eventschema/proto/v1/events.proto

package eventschemav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType identifies the kind of event carried by an Envelope.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED  EventType = 0
	EventType_EVENT_TYPE_PROMPT       EventType = 1
	EventType_EVENT_TYPE_WORKFLOW     EventType = 2
	EventType_EVENT_TYPE_OPTIMIZATION EventType = 3
	EventType_EVENT_TYPE_COACHING     EventType = 4
	EventType_EVENT_TYPE_DECISION     EventType = 7
	EventType_EVENT_TYPE_OUTCOME      EventType = 8
	EventType_EVENT_TYPE_EXPERIMENT   EventType = 9
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PROMPT",
		2: "EVENT_TYPE_WORKFLOW",
		3: "EVENT_TYPE_OPTIMIZATION",
		4: "EVENT_TYPE_COACHING",
		7: "EVENT_TYPE_DECISION",
		8: "EVENT_TYPE_OUTCOME",
		9: "EVENT_TYPE_EXPERIMENT",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":  0,
		"EVENT_TYPE_PROMPT":       1,
		"EVENT_TYPE_WORKFLOW":     2,
		"EVENT_TYPE_OPTIMIZATION": 3,
		"EVENT_TYPE_COACHING":     4,
		"EVENT_TYPE_DECISION":     7,
		"EVENT_TYPE_OUTCOME":      8,
		"EVENT_TYPE_EXPERIMENT":   9,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_eventschema_proto_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_pkg_eventschema_proto_v1_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{0}
}

// Provider identifies the upstream LLM provider.
type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_PROVIDER_OPENAI      Provider = 1
	Provider_PROVIDER_ANTHROPIC   Provider = 2
	Provider_PROVIDER_GEMINI      Provider = 3
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_OPENAI",
		2: "PROVIDER_ANTHROPIC",
		3: "PROVIDER_GEMINI",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"PROVIDER_OPENAI":      1,
		"PROVIDER_ANTHROPIC":   2,
		"PROVIDER_GEMINI":      3,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_eventschema_proto_v1_events_proto_enumTypes[1].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_pkg_eventschema_proto_v1_events_proto_enumTypes[1]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{1}
}

// WorkflowState describes the lifecycle phase of a WorkflowEvent.
type WorkflowState int32

const (
	WorkflowState_WORKFLOW_STATE_UNSPECIFIED WorkflowState = 0
	WorkflowState_WORKFLOW_STATE_STARTED     WorkflowState = 1
	WorkflowState_WORKFLOW_STATE_PROGRESS    WorkflowState = 2
	WorkflowState_WORKFLOW_STATE_COMPLETED   WorkflowState = 3
	WorkflowState_WORKFLOW_STATE_FAILED      WorkflowState = 4
)

// Enum value maps for WorkflowState.
var (
	WorkflowState_name = map[int32]string{
		0: "WORKFLOW_STATE_UNSPECIFIED",
		1: "WORKFLOW_STATE_STARTED",
		2: "WORKFLOW_STATE_PROGRESS",
		3: "WORKFLOW_STATE_COMPLETED",
		4: "WORKFLOW_STATE_FAILED",
	}
	WorkflowState_value = map[string]int32{
		"WORKFLOW_STATE_UNSPECIFIED": 0,
		"WORKFLOW_STATE_STARTED":     1,
		"WORKFLOW_STATE_PROGRESS":    2,
		"WORKFLOW_STATE_COMPLETED":   3,
		"WORKFLOW_STATE_FAILED":      4,
	}
)

func (x WorkflowState) Enum() *WorkflowState {
	p := new(WorkflowState)
	*p = x
	return p
}

func (x WorkflowState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_eventschema_proto_v1_events_proto_enumTypes[2].Descriptor()
}

func (WorkflowState) Type() protoreflect.EnumType {
	return &file_pkg_eventschema_proto_v1_events_proto_enumTypes[2]
}

func (x WorkflowState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowState.Descriptor instead.
func (WorkflowState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{2}
}

// OptimizationType identifies the optimizer that produced an event.
type OptimizationType int32

const (
	OptimizationType_OPTIMIZATION_TYPE_UNSPECIFIED     OptimizationType = 0
	OptimizationType_OPTIMIZATION_TYPE_PROMPT_COMPRESS OptimizationType = 1
	OptimizationType_OPTIMIZATION_TYPE_DEDUPE          OptimizationType = 2
	OptimizationType_OPTIMIZATION_TYPE_RETRIEVAL_PRUNE OptimizationType = 3
	OptimizationType_OPTIMIZATION_TYPE_CONTEXT_TRIM    OptimizationType = 4
	OptimizationType_OPTIMIZATION_TYPE_SYSTEM_DEDUPE   OptimizationType = 5
	OptimizationType_OPTIMIZATION_TYPE_ROUTER          OptimizationType = 6
	OptimizationType_OPTIMIZATION_TYPE_CACHE_REUSE     OptimizationType = 7
)

// Enum value maps for OptimizationType.
var (
	OptimizationType_name = map[int32]string{
		0: "OPTIMIZATION_TYPE_UNSPECIFIED",
		1: "OPTIMIZATION_TYPE_PROMPT_COMPRESS",
		2: "OPTIMIZATION_TYPE_DEDUPE",
		3: "OPTIMIZATION_TYPE_RETRIEVAL_PRUNE",
		4: "OPTIMIZATION_TYPE_CONTEXT_TRIM",
		5: "OPTIMIZATION_TYPE_SYSTEM_DEDUPE",
		6: "OPTIMIZATION_TYPE_ROUTER",
		7: "OPTIMIZATION_TYPE_CACHE_REUSE",
	}
	OptimizationType_value = map[string]int32{
		"OPTIMIZATION_TYPE_UNSPECIFIED":     0,
		"OPTIMIZATION_TYPE_PROMPT_COMPRESS": 1,
		"OPTIMIZATION_TYPE_DEDUPE":          2,
		"OPTIMIZATION_TYPE_RETRIEVAL_PRUNE": 3,
		"OPTIMIZATION_TYPE_CONTEXT_TRIM":    4,
		"OPTIMIZATION_TYPE_SYSTEM_DEDUPE":   5,
		"OPTIMIZATION_TYPE_ROUTER":          6,
		"OPTIMIZATION_TYPE_CACHE_REUSE":     7,
	}
)

func (x OptimizationType) Enum() *OptimizationType {
	p := new(OptimizationType)
	*p = x
	return p
}

func (x OptimizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptimizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_eventschema_proto_v1_events_proto_enumTypes[3].Descriptor()
}

func (OptimizationType) Type() protoreflect.EnumType {
	return &file_pkg_eventschema_proto_v1_events_proto_enumTypes[3]
}

func (x OptimizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptimizationType.Descriptor instead.
func (OptimizationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{3}
}

type OptimizationMode int32

const (
	OptimizationMode_OPTIMIZATION_MODE_UNSPECIFIED OptimizationMode = 0
	OptimizationMode_OPTIMIZATION_MODE_PASSIVE     OptimizationMode = 1
	OptimizationMode_OPTIMIZATION_MODE_INTERACTIVE OptimizationMode = 2
	OptimizationMode_OPTIMIZATION_MODE_REPLAY      OptimizationMode = 3
)

// Enum value maps for OptimizationMode.
var (
	OptimizationMode_name = map[int32]string{
		0: "OPTIMIZATION_MODE_UNSPECIFIED",
		1: "OPTIMIZATION_MODE_PASSIVE",
		2: "OPTIMIZATION_MODE_INTERACTIVE",
		3: "OPTIMIZATION_MODE_REPLAY",
	}
	OptimizationMode_value = map[string]int32{
		"OPTIMIZATION_MODE_UNSPECIFIED": 0,
		"OPTIMIZATION_MODE_PASSIVE":     1,
		"OPTIMIZATION_MODE_INTERACTIVE": 2,
		"OPTIMIZATION_MODE_REPLAY":      3,
	}
)

func (x OptimizationMode) Enum() *OptimizationMode {
	p := new(OptimizationMode)
	*p = x
	return p
}

func (x OptimizationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptimizationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_eventschema_proto_v1_events_proto_enumTypes[4].Descriptor()
}

func (OptimizationMode) Type() protoreflect.EnumType {
	return &file_pkg_eventschema_proto_v1_events_proto_enumTypes[4]
}

func (x OptimizationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptimizationMode.Descriptor instead.
func (OptimizationMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{4}
}

type OptimizationDecision int32

const (
	OptimizationDecision_OPTIMIZATION_DECISION_UNSPECIFIED OptimizationDecision = 0
	OptimizationDecision_OPTIMIZATION_DECISION_APPLIED     OptimizationDecision = 1
	OptimizationDecision_OPTIMIZATION_DECISION_ACCEPTED    OptimizationDecision = 2
	OptimizationDecision_OPTIMIZATION_DECISION_REJECTED    OptimizationDecision = 3
	OptimizationDecision_OPTIMIZATION_DECISION_SKIPPED     OptimizationDecision = 4
)

// Enum value maps for OptimizationDecision.
var (
	OptimizationDecision_name = map[int32]string{
		0: "OPTIMIZATION_DECISION_UNSPECIFIED",
		1: "OPTIMIZATION_DECISION_APPLIED",
		2: "OPTIMIZATION_DECISION_ACCEPTED",
		3: "OPTIMIZATION_DECISION_REJECTED",
		4: "OPTIMIZATION_DECISION_SKIPPED",
	}
	OptimizationDecision_value = map[string]int32{
		"OPTIMIZATION_DECISION_UNSPECIFIED": 0,
		"OPTIMIZATION_DECISION_APPLIED":     1,
		"OPTIMIZATION_DECISION_ACCEPTED":    2,
		"OPTIMIZATION_DECISION_REJECTED":    3,
		"OPTIMIZATION_DECISION_SKIPPED":     4,
	}
)

func (x OptimizationDecision) Enum() *OptimizationDecision {
	p := new(OptimizationDecision)
	*p = x
	return p
}

func (x OptimizationDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptimizationDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_eventschema_proto_v1_events_proto_enumTypes[5].Descriptor()
}

func (OptimizationDecision) Type() protoreflect.EnumType {
	return &file_pkg_eventschema_proto_v1_events_proto_enumTypes[5]
}

func (x OptimizationDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptimizationDecision.Descriptor instead.
func (OptimizationDecision) EnumDescriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{5}
}

type CoachingRecommendationKind int32

const (
	CoachingRecommendationKind_COACHING_KIND_UNSPECIFIED        CoachingRecommendationKind = 0
	CoachingRecommendationKind_COACHING_KIND_REDUCE_PROMPT_SIZE CoachingRecommendationKind = 1
	CoachingRecommendationKind_COACHING_KIND_TRIM_CONTEXT       CoachingRecommendationKind = 2
	CoachingRecommendationKind_COACHING_KIND_SHRINK_RETRIEVAL   CoachingRecommendationKind = 3
	CoachingRecommendationKind_COACHING_KIND_REUSE_CACHE        CoachingRecommendationKind = 4
	CoachingRecommendationKind_COACHING_KIND_SWITCH_MODEL       CoachingRecommendationKind = 5
	CoachingRecommendationKind_COACHING_KIND_BATCH_REQUESTS     CoachingRecommendationKind = 6
	CoachingRecommendationKind_COACHING_KIND_BREAK_RECURSION    CoachingRecommendationKind = 7
)

// Enum value maps for CoachingRecommendationKind.
var (
	CoachingRecommendationKind_name = map[int32]string{
		0: "COACHING_KIND_UNSPECIFIED",
		1: "COACHING_KIND_REDUCE_PROMPT_SIZE",
		2: "COACHING_KIND_TRIM_CONTEXT",
		3: "COACHING_KIND_SHRINK_RETRIEVAL",
		4: "COACHING_KIND_REUSE_CACHE",
		5: "COACHING_KIND_SWITCH_MODEL",
		6: "COACHING_KIND_BATCH_REQUESTS",
		7: "COACHING_KIND_BREAK_RECURSION",
	}
	CoachingRecommendationKind_value = map[string]int32{
		"COACHING_KIND_UNSPECIFIED":        0,
		"COACHING_KIND_REDUCE_PROMPT_SIZE": 1,
		"COACHING_KIND_TRIM_CONTEXT":       2,
		"COACHING_KIND_SHRINK_RETRIEVAL":   3,
		"COACHING_KIND_REUSE_CACHE":        4,
		"COACHING_KIND_SWITCH_MODEL":       5,
		"COACHING_KIND_BATCH_REQUESTS":     6,
		"COACHING_KIND_BREAK_RECURSION":    7,
	}
)

func (x CoachingRecommendationKind) Enum() *CoachingRecommendationKind {
	p := new(CoachingRecommendationKind)
	*p = x
	return p
}

func (x CoachingRecommendationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoachingRecommendationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_eventschema_proto_v1_events_proto_enumTypes[6].Descriptor()
}

func (CoachingRecommendationKind) Type() protoreflect.EnumType {
	return &file_pkg_eventschema_proto_v1_events_proto_enumTypes[6]
}

func (x CoachingRecommendationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoachingRecommendationKind.Descriptor instead.
func (CoachingRecommendationKind) EnumDescriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{6}
}

// Envelope is the common header carried by every TokenOps event.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Type          EventType              `protobuf:"varint,3,opt,name=type,proto3,enum=tokenops.eventschema.v1.EventType" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Correlation   *Correlation           `protobuf:"bytes,9,opt,name=correlation,proto3" json:"correlation,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Prompt
	//	*Envelope_Workflow
	//	*Envelope_Optimization
	//	*Envelope_Coaching
	//	*Envelope_Decision
	//	*Envelope_Outcome
	//	*Envelope_Experiment
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Envelope) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Envelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Envelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Envelope) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Envelope) GetCorrelation() *Correlation {
	if x != nil {
		return x.Correlation
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetPrompt() *PromptEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

func (x *Envelope) GetWorkflow() *WorkflowEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Workflow); ok {
			return x.Workflow
		}
	}
	return nil
}

func (x *Envelope) GetOptimization() *OptimizationEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Optimization); ok {
			return x.Optimization
		}
	}
	return nil
}

func (x *Envelope) GetCoaching() *CoachingEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Coaching); ok {
			return x.Coaching
		}
	}
	return nil
}

func (x *Envelope) GetDecision() *DecisionEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Decision); ok {
			return x.Decision
		}
	}
	return nil
}

func (x *Envelope) GetOutcome() *OutcomeEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Outcome); ok {
			return x.Outcome
		}
	}
	return nil
}

func (x *Envelope) GetExperiment() *ExperimentEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Experiment); ok {
			return x.Experiment
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Prompt struct {
	Prompt *PromptEvent `protobuf:"bytes,100,opt,name=prompt,proto3,oneof"`
}

type Envelope_Workflow struct {
	Workflow *WorkflowEvent `protobuf:"bytes,101,opt,name=workflow,proto3,oneof"`
}

type Envelope_Optimization struct {
	Optimization *OptimizationEvent `protobuf:"bytes,102,opt,name=optimization,proto3,oneof"`
}

type Envelope_Coaching struct {
	Coaching *CoachingEvent `protobuf:"bytes,103,opt,name=coaching,proto3,oneof"`
}

type Envelope_Decision struct {
	Decision *DecisionEvent `protobuf:"bytes,106,opt,name=decision,proto3,oneof"`
}

type Envelope_Outcome struct {
	Outcome *OutcomeEvent `protobuf:"bytes,107,opt,name=outcome,proto3,oneof"`
}

type Envelope_Experiment struct {
	Experiment *ExperimentEvent `protobuf:"bytes,108,opt,name=experiment,proto3,oneof"`
}

func (*Envelope_Prompt) isEnvelope_Payload() {}

func (*Envelope_Workflow) isEnvelope_Payload() {}

func (*Envelope_Optimization) isEnvelope_Payload() {}

func (*Envelope_Coaching) isEnvelope_Payload() {}

func (*Envelope_Decision) isEnvelope_Payload() {}

func (*Envelope_Outcome) isEnvelope_Payload() {}

func (*Envelope_Experiment) isEnvelope_Payload() {}

type Correlation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DecisionId     string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	InterventionId string                 `protobuf:"bytes,2,opt,name=intervention_id,json=interventionId,proto3" json:"intervention_id,omitempty"`
	ExperimentId   string                 `protobuf:"bytes,3,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Correlation) Reset() {
	*x = Correlation{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Correlation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Correlation) ProtoMessage() {}

func (x *Correlation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Correlation.ProtoReflect.Descriptor instead.
func (*Correlation) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Correlation) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Correlation) GetInterventionId() string {
	if x != nil {
		return x.InterventionId
	}
	return ""
}

func (x *Correlation) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

type ResourceOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceOption) Reset() {
	*x = ResourceOption{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceOption) ProtoMessage() {}

func (x *ResourceOption) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceOption.ProtoReflect.Descriptor instead.
func (*ResourceOption) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceOption) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ResourceOption) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ResourceOption) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EvidenceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	FreshUntil    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=fresh_until,json=freshUntil,proto3" json:"fresh_until,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Scope         string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	Caveat        string                 `protobuf:"bytes,8,opt,name=caveat,proto3" json:"caveat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceRef) Reset() {
	*x = EvidenceRef{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceRef) ProtoMessage() {}

func (x *EvidenceRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceRef.ProtoReflect.Descriptor instead.
func (*EvidenceRef) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *EvidenceRef) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EvidenceRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EvidenceRef) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EvidenceRef) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *EvidenceRef) GetFreshUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.FreshUntil
	}
	return nil
}

func (x *EvidenceRef) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *EvidenceRef) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *EvidenceRef) GetCaveat() string {
	if x != nil {
		return x.Caveat
	}
	return ""
}

type DecisionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Stage         string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	Alternatives  []*ResourceOption      `protobuf:"bytes,3,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	Selected      *ResourceOption        `protobuf:"bytes,4,opt,name=selected,proto3" json:"selected,omitempty"`
	Evidence      []*EvidenceRef         `protobuf:"bytes,5,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Policy        string                 `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	Authority     string                 `protobuf:"bytes,7,opt,name=authority,proto3" json:"authority,omitempty"`
	Confidence    float64                `protobuf:"fixed64,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Rationale     string                 `protobuf:"bytes,9,opt,name=rationale,proto3" json:"rationale,omitempty"`
	Executable    bool                   `protobuf:"varint,10,opt,name=executable,proto3" json:"executable,omitempty"`
	Adapter       string                 `protobuf:"bytes,11,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,12,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionEvent) Reset() {
	*x = DecisionEvent{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionEvent) ProtoMessage() {}

func (x *DecisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionEvent.ProtoReflect.Descriptor instead.
func (*DecisionEvent) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DecisionEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DecisionEvent) GetAlternatives() []*ResourceOption {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *DecisionEvent) GetSelected() *ResourceOption {
	if x != nil {
		return x.Selected
	}
	return nil
}

func (x *DecisionEvent) GetEvidence() []*EvidenceRef {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *DecisionEvent) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *DecisionEvent) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *DecisionEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DecisionEvent) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *DecisionEvent) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *DecisionEvent) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *DecisionEvent) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type OutcomeMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Caveat        string                 `protobuf:"bytes,7,opt,name=caveat,proto3" json:"caveat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutcomeMetric) Reset() {
	*x = OutcomeMetric{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutcomeMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeMetric) ProtoMessage() {}

func (x *OutcomeMetric) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeMetric.ProtoReflect.Descriptor instead.
func (*OutcomeMetric) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *OutcomeMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutcomeMetric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *OutcomeMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *OutcomeMetric) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OutcomeMetric) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *OutcomeMetric) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *OutcomeMetric) GetCaveat() string {
	if x != nil {
		return x.Caveat
	}
	return ""
}

type OutcomeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Assessment    string                 `protobuf:"bytes,2,opt,name=assessment,proto3" json:"assessment,omitempty"`
	Caveat        string                 `protobuf:"bytes,3,opt,name=caveat,proto3" json:"caveat,omitempty"`
	Evidence      []*EvidenceRef         `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Metrics       []*OutcomeMetric       `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutcomeEvent) Reset() {
	*x = OutcomeEvent{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutcomeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeEvent) ProtoMessage() {}

func (x *OutcomeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeEvent.ProtoReflect.Descriptor instead.
func (*OutcomeEvent) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *OutcomeEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *OutcomeEvent) GetAssessment() string {
	if x != nil {
		return x.Assessment
	}
	return ""
}

func (x *OutcomeEvent) GetCaveat() string {
	if x != nil {
		return x.Caveat
	}
	return ""
}

func (x *OutcomeEvent) GetEvidence() []*EvidenceRef {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *OutcomeEvent) GetMetrics() []*OutcomeMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ExperimentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Baseline      *ResourceOption        `protobuf:"bytes,3,opt,name=baseline,proto3" json:"baseline,omitempty"`
	Variant       *ResourceOption        `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`
	Assignment    string                 `protobuf:"bytes,5,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Pair          int32                  `protobuf:"varint,6,opt,name=pair,proto3" json:"pair,omitempty"`
	MaxPairs      int32                  `protobuf:"varint,7,opt,name=max_pairs,json=maxPairs,proto3" json:"max_pairs,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,10,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentEvent) Reset() {
	*x = ExperimentEvent{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentEvent) ProtoMessage() {}

func (x *ExperimentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentEvent.ProtoReflect.Descriptor instead.
func (*ExperimentEvent) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *ExperimentEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ExperimentEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExperimentEvent) GetBaseline() *ResourceOption {
	if x != nil {
		return x.Baseline
	}
	return nil
}

func (x *ExperimentEvent) GetVariant() *ResourceOption {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *ExperimentEvent) GetAssignment() string {
	if x != nil {
		return x.Assignment
	}
	return ""
}

func (x *ExperimentEvent) GetPair() int32 {
	if x != nil {
		return x.Pair
	}
	return 0
}

func (x *ExperimentEvent) GetMaxPairs() int32 {
	if x != nil {
		return x.MaxPairs
	}
	return 0
}

func (x *ExperimentEvent) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *ExperimentEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ExperimentEvent) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type PromptEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PromptHash        string                 `protobuf:"bytes,1,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`
	Provider          Provider               `protobuf:"varint,2,opt,name=provider,proto3,enum=tokenops.eventschema.v1.Provider" json:"provider,omitempty"`
	RequestModel      string                 `protobuf:"bytes,3,opt,name=request_model,json=requestModel,proto3" json:"request_model,omitempty"`
	ResponseModel     string                 `protobuf:"bytes,4,opt,name=response_model,json=responseModel,proto3" json:"response_model,omitempty"`
	InputTokens       int64                  `protobuf:"varint,10,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens      int64                  `protobuf:"varint,11,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens       int64                  `protobuf:"varint,12,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CachedInputTokens int64                  `protobuf:"varint,13,opt,name=cached_input_tokens,json=cachedInputTokens,proto3" json:"cached_input_tokens,omitempty"`
	ContextSize       int64                  `protobuf:"varint,20,opt,name=context_size,json=contextSize,proto3" json:"context_size,omitempty"`
	MaxOutputTokens   int64                  `protobuf:"varint,21,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	Latency           *durationpb.Duration   `protobuf:"bytes,30,opt,name=latency,proto3" json:"latency,omitempty"`
	TimeToFirstToken  *durationpb.Duration   `protobuf:"bytes,31,opt,name=time_to_first_token,json=timeToFirstToken,proto3" json:"time_to_first_token,omitempty"`
	Streaming         bool                   `protobuf:"varint,40,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Status            int32                  `protobuf:"varint,41,opt,name=status,proto3" json:"status,omitempty"`
	FinishReason      string                 `protobuf:"bytes,42,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,43,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	CacheHit          bool                   `protobuf:"varint,44,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	CostUsd           float64                `protobuf:"fixed64,50,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	WorkflowId        string                 `protobuf:"bytes,60,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	AgentId           string                 `protobuf:"bytes,61,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,62,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId            string                 `protobuf:"bytes,63,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PromptEvent) Reset() {
	*x = PromptEvent{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptEvent) ProtoMessage() {}

func (x *PromptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptEvent.ProtoReflect.Descriptor instead.
func (*PromptEvent) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *PromptEvent) GetPromptHash() string {
	if x != nil {
		return x.PromptHash
	}
	return ""
}

func (x *PromptEvent) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *PromptEvent) GetRequestModel() string {
	if x != nil {
		return x.RequestModel
	}
	return ""
}

func (x *PromptEvent) GetResponseModel() string {
	if x != nil {
		return x.ResponseModel
	}
	return ""
}

func (x *PromptEvent) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *PromptEvent) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *PromptEvent) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *PromptEvent) GetCachedInputTokens() int64 {
	if x != nil {
		return x.CachedInputTokens
	}
	return 0
}

func (x *PromptEvent) GetContextSize() int64 {
	if x != nil {
		return x.ContextSize
	}
	return 0
}

func (x *PromptEvent) GetMaxOutputTokens() int64 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *PromptEvent) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *PromptEvent) GetTimeToFirstToken() *durationpb.Duration {
	if x != nil {
		return x.TimeToFirstToken
	}
	return nil
}

func (x *PromptEvent) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *PromptEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PromptEvent) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *PromptEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PromptEvent) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *PromptEvent) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *PromptEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *PromptEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PromptEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PromptEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WorkflowEvent struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId             string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	AgentId                string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ParentWorkflowId       string                 `protobuf:"bytes,3,opt,name=parent_workflow_id,json=parentWorkflowId,proto3" json:"parent_workflow_id,omitempty"`
	State                  WorkflowState          `protobuf:"varint,4,opt,name=state,proto3,enum=tokenops.eventschema.v1.WorkflowState" json:"state,omitempty"`
	StepCount              int64                  `protobuf:"varint,10,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	CumulativeInputTokens  int64                  `protobuf:"varint,11,opt,name=cumulative_input_tokens,json=cumulativeInputTokens,proto3" json:"cumulative_input_tokens,omitempty"`
	CumulativeOutputTokens int64                  `protobuf:"varint,12,opt,name=cumulative_output_tokens,json=cumulativeOutputTokens,proto3" json:"cumulative_output_tokens,omitempty"`
	CumulativeTotalTokens  int64                  `protobuf:"varint,13,opt,name=cumulative_total_tokens,json=cumulativeTotalTokens,proto3" json:"cumulative_total_tokens,omitempty"`
	CumulativeCostUsd      float64                `protobuf:"fixed64,14,opt,name=cumulative_cost_usd,json=cumulativeCostUsd,proto3" json:"cumulative_cost_usd,omitempty"`
	Duration               *durationpb.Duration   `protobuf:"bytes,20,opt,name=duration,proto3" json:"duration,omitempty"`
	ErrorCode              string                 `protobuf:"bytes,30,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WorkflowEvent) Reset() {
	*x = WorkflowEvent{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEvent) ProtoMessage() {}

func (x *WorkflowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEvent.ProtoReflect.Descriptor instead.
func (*WorkflowEvent) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WorkflowEvent) GetParentWorkflowId() string {
	if x != nil {
		return x.ParentWorkflowId
	}
	return ""
}

func (x *WorkflowEvent) GetState() WorkflowState {
	if x != nil {
		return x.State
	}
	return WorkflowState_WORKFLOW_STATE_UNSPECIFIED
}

func (x *WorkflowEvent) GetStepCount() int64 {
	if x != nil {
		return x.StepCount
	}
	return 0
}

func (x *WorkflowEvent) GetCumulativeInputTokens() int64 {
	if x != nil {
		return x.CumulativeInputTokens
	}
	return 0
}

func (x *WorkflowEvent) GetCumulativeOutputTokens() int64 {
	if x != nil {
		return x.CumulativeOutputTokens
	}
	return 0
}

func (x *WorkflowEvent) GetCumulativeTotalTokens() int64 {
	if x != nil {
		return x.CumulativeTotalTokens
	}
	return 0
}

func (x *WorkflowEvent) GetCumulativeCostUsd() float64 {
	if x != nil {
		return x.CumulativeCostUsd
	}
	return 0
}

func (x *WorkflowEvent) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *WorkflowEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type OptimizationEvent struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PromptHash             string                 `protobuf:"bytes,1,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`
	Type                   OptimizationType       `protobuf:"varint,2,opt,name=type,proto3,enum=tokenops.eventschema.v1.OptimizationType" json:"type,omitempty"`
	Mode                   OptimizationMode       `protobuf:"varint,3,opt,name=mode,proto3,enum=tokenops.eventschema.v1.OptimizationMode" json:"mode,omitempty"`
	EstimatedSavingsTokens int64                  `protobuf:"varint,10,opt,name=estimated_savings_tokens,json=estimatedSavingsTokens,proto3" json:"estimated_savings_tokens,omitempty"`
	EstimatedSavingsUsd    float64                `protobuf:"fixed64,11,opt,name=estimated_savings_usd,json=estimatedSavingsUsd,proto3" json:"estimated_savings_usd,omitempty"`
	QualityScore           float64                `protobuf:"fixed64,12,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Decision               OptimizationDecision   `protobuf:"varint,20,opt,name=decision,proto3,enum=tokenops.eventschema.v1.OptimizationDecision" json:"decision,omitempty"`
	Reason                 string                 `protobuf:"bytes,21,opt,name=reason,proto3" json:"reason,omitempty"`
	LatencyImpactNs        int64                  `protobuf:"varint,30,opt,name=latency_impact_ns,json=latencyImpactNs,proto3" json:"latency_impact_ns,omitempty"`
	WorkflowId             string                 `protobuf:"bytes,40,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	AgentId                string                 `protobuf:"bytes,41,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OptimizationEvent) Reset() {
	*x = OptimizationEvent{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationEvent) ProtoMessage() {}

func (x *OptimizationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationEvent.ProtoReflect.Descriptor instead.
func (*OptimizationEvent) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *OptimizationEvent) GetPromptHash() string {
	if x != nil {
		return x.PromptHash
	}
	return ""
}

func (x *OptimizationEvent) GetType() OptimizationType {
	if x != nil {
		return x.Type
	}
	return OptimizationType_OPTIMIZATION_TYPE_UNSPECIFIED
}

func (x *OptimizationEvent) GetMode() OptimizationMode {
	if x != nil {
		return x.Mode
	}
	return OptimizationMode_OPTIMIZATION_MODE_UNSPECIFIED
}

func (x *OptimizationEvent) GetEstimatedSavingsTokens() int64 {
	if x != nil {
		return x.EstimatedSavingsTokens
	}
	return 0
}

func (x *OptimizationEvent) GetEstimatedSavingsUsd() float64 {
	if x != nil {
		return x.EstimatedSavingsUsd
	}
	return 0
}

func (x *OptimizationEvent) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *OptimizationEvent) GetDecision() OptimizationDecision {
	if x != nil {
		return x.Decision
	}
	return OptimizationDecision_OPTIMIZATION_DECISION_UNSPECIFIED
}

func (x *OptimizationEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OptimizationEvent) GetLatencyImpactNs() int64 {
	if x != nil {
		return x.LatencyImpactNs
	}
	return 0
}

func (x *OptimizationEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *OptimizationEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type CoachingEvent struct {
	state                  protoimpl.MessageState     `protogen:"open.v1"`
	SessionId              string                     `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkflowId             string                     `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	AgentId                string                     `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Kind                   CoachingRecommendationKind `protobuf:"varint,4,opt,name=kind,proto3,enum=tokenops.eventschema.v1.CoachingRecommendationKind" json:"kind,omitempty"`
	Summary                string                     `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Details                string                     `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	EstimatedSavingsTokens int64                      `protobuf:"varint,10,opt,name=estimated_savings_tokens,json=estimatedSavingsTokens,proto3" json:"estimated_savings_tokens,omitempty"`
	EstimatedSavingsUsd    float64                    `protobuf:"fixed64,11,opt,name=estimated_savings_usd,json=estimatedSavingsUsd,proto3" json:"estimated_savings_usd,omitempty"`
	EfficiencyScore        float64                    `protobuf:"fixed64,20,opt,name=efficiency_score,json=efficiencyScore,proto3" json:"efficiency_score,omitempty"`
	EfficiencyDelta        float64                    `protobuf:"fixed64,21,opt,name=efficiency_delta,json=efficiencyDelta,proto3" json:"efficiency_delta,omitempty"`
	ReplayMetadata         map[string]string          `protobuf:"bytes,30,rep,name=replay_metadata,json=replayMetadata,proto3" json:"replay_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Decision               OptimizationDecision       `protobuf:"varint,31,opt,name=decision,proto3,enum=tokenops.eventschema.v1.OptimizationDecision" json:"decision,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CoachingEvent) Reset() {
	*x = CoachingEvent{}
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoachingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoachingEvent) ProtoMessage() {}

func (x *CoachingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_eventschema_proto_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoachingEvent.ProtoReflect.Descriptor instead.
func (*CoachingEvent) Descriptor() ([]byte, []int) {
	return file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *CoachingEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CoachingEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CoachingEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CoachingEvent) GetKind() CoachingRecommendationKind {
	if x != nil {
		return x.Kind
	}
	return CoachingRecommendationKind_COACHING_KIND_UNSPECIFIED
}

func (x *CoachingEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CoachingEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *CoachingEvent) GetEstimatedSavingsTokens() int64 {
	if x != nil {
		return x.EstimatedSavingsTokens
	}
	return 0
}

func (x *CoachingEvent) GetEstimatedSavingsUsd() float64 {
	if x != nil {
		return x.EstimatedSavingsUsd
	}
	return 0
}

func (x *CoachingEvent) GetEfficiencyScore() float64 {
	if x != nil {
		return x.EfficiencyScore
	}
	return 0
}

func (x *CoachingEvent) GetEfficiencyDelta() float64 {
	if x != nil {
		return x.EfficiencyDelta
	}
	return 0
}

func (x *CoachingEvent) GetReplayMetadata() map[string]string {
	if x != nil {
		return x.ReplayMetadata
	}
	return nil
}

func (x *CoachingEvent) GetDecision() OptimizationDecision {
	if x != nil {
		return x.Decision
	}
	return OptimizationDecision_OPTIMIZATION_DECISION_UNSPECIFIED
}

var File_pkg_eventschema_proto_v1_events_proto protoreflect.FileDescriptor

const file_pkg_eventschema_proto_v1_events_proto_rawDesc = "" +
	"\n" +
	"%pkg/eventschema/proto/v1/events.proto\x12\x17tokenops.eventschema.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd7\a\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\tR\rschemaVersion\x126\n" +
	"\x04type\x18\x03 \x01(\x0e2\".tokenops.eventschema.v1.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12Q\n" +
	"\n" +
	"attributes\x18\b \x03(\v21.tokenops.eventschema.v1.Envelope.AttributesEntryR\n" +
	"attributes\x12F\n" +
	"\vcorrelation\x18\t \x01(\v2$.tokenops.eventschema.v1.CorrelationR\vcorrelation\x12>\n" +
	"\x06prompt\x18d \x01(\v2$.tokenops.eventschema.v1.PromptEventH\x00R\x06prompt\x12D\n" +
	"\bworkflow\x18e \x01(\v2&.tokenops.eventschema.v1.WorkflowEventH\x00R\bworkflow\x12P\n" +
	"\foptimization\x18f \x01(\v2*.tokenops.eventschema.v1.OptimizationEventH\x00R\foptimization\x12D\n" +
	"\bcoaching\x18g \x01(\v2&.tokenops.eventschema.v1.CoachingEventH\x00R\bcoaching\x12D\n" +
	"\bdecision\x18j \x01(\v2&.tokenops.eventschema.v1.DecisionEventH\x00R\bdecision\x12A\n" +
	"\aoutcome\x18k \x01(\v2%.tokenops.eventschema.v1.OutcomeEventH\x00R\aoutcome\x12J\n" +
	"\n" +
	"experiment\x18l \x01(\v2(.tokenops.eventschema.v1.ExperimentEventH\x00R\n" +
	"experiment\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"|\n" +
	"\vCorrelation\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12'\n" +
	"\x0fintervention_id\x18\x02 \x01(\tR\x0einterventionId\x12#\n" +
	"\rexperiment_id\x18\x03 \x01(\tR\fexperimentId\"Z\n" +
	"\x0eResourceOption\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x9c\x02\n" +
	"\vEvidenceRef\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12;\n" +
	"\vfresh_until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"freshUntil\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12\x16\n" +
	"\x06caveat\x18\b \x01(\tR\x06caveat\"\xdd\x03\n" +
	"\rDecisionEvent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12K\n" +
	"\falternatives\x18\x03 \x03(\v2'.tokenops.eventschema.v1.ResourceOptionR\falternatives\x12C\n" +
	"\bselected\x18\x04 \x01(\v2'.tokenops.eventschema.v1.ResourceOptionR\bselected\x12@\n" +
	"\bevidence\x18\x05 \x03(\v2$.tokenops.eventschema.v1.EvidenceRefR\bevidence\x12\x16\n" +
	"\x06policy\x18\x06 \x01(\tR\x06policy\x12\x1c\n" +
	"\tauthority\x18\a \x01(\tR\tauthority\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\trationale\x18\t \x01(\tR\trationale\x12\x1e\n" +
	"\n" +
	"executable\x18\n" +
	" \x01(\bR\n" +
	"executable\x12\x18\n" +
	"\aadapter\x18\v \x01(\tR\aadapter\x12 \n" +
	"\vfingerprint\x18\f \x01(\tR\vfingerprint\"\xda\x01\n" +
	"\rOutcomeMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x16\n" +
	"\x06caveat\x18\a \x01(\tR\x06caveat\"\xe2\x01\n" +
	"\fOutcomeEvent\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x1e\n" +
	"\n" +
	"assessment\x18\x02 \x01(\tR\n" +
	"assessment\x12\x16\n" +
	"\x06caveat\x18\x03 \x01(\tR\x06caveat\x12@\n" +
	"\bevidence\x18\x04 \x03(\v2$.tokenops.eventschema.v1.EvidenceRefR\bevidence\x12@\n" +
	"\ametrics\x18\x05 \x03(\v2&.tokenops.eventschema.v1.OutcomeMetricR\ametrics\"\x83\x03\n" +
	"\x0fExperimentEvent\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12C\n" +
	"\bbaseline\x18\x03 \x01(\v2'.tokenops.eventschema.v1.ResourceOptionR\bbaseline\x12A\n" +
	"\avariant\x18\x04 \x01(\v2'.tokenops.eventschema.v1.ResourceOptionR\avariant\x12\x1e\n" +
	"\n" +
	"assignment\x18\x05 \x01(\tR\n" +
	"assignment\x12\x12\n" +
	"\x04pair\x18\x06 \x01(\x05R\x04pair\x12\x1b\n" +
	"\tmax_pairs\x18\a \x01(\x05R\bmaxPairs\x123\n" +
	"\aends_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12 \n" +
	"\vfingerprint\x18\n" +
	" \x01(\tR\vfingerprint\"\xc8\x06\n" +
	"\vPromptEvent\x12\x1f\n" +
	"\vprompt_hash\x18\x01 \x01(\tR\n" +
	"promptHash\x12=\n" +
	"\bprovider\x18\x02 \x01(\x0e2!.tokenops.eventschema.v1.ProviderR\bprovider\x12#\n" +
	"\rrequest_model\x18\x03 \x01(\tR\frequestModel\x12%\n" +
	"\x0eresponse_model\x18\x04 \x01(\tR\rresponseModel\x12!\n" +
	"\finput_tokens\x18\n" +
	" \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\v \x01(\x03R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\f \x01(\x03R\vtotalTokens\x12.\n" +
	"\x13cached_input_tokens\x18\r \x01(\x03R\x11cachedInputTokens\x12!\n" +
	"\fcontext_size\x18\x14 \x01(\x03R\vcontextSize\x12*\n" +
	"\x11max_output_tokens\x18\x15 \x01(\x03R\x0fmaxOutputTokens\x123\n" +
	"\alatency\x18\x1e \x01(\v2\x19.google.protobuf.DurationR\alatency\x12H\n" +
	"\x13time_to_first_token\x18\x1f \x01(\v2\x19.google.protobuf.DurationR\x10timeToFirstToken\x12\x1c\n" +
	"\tstreaming\x18( \x01(\bR\tstreaming\x12\x16\n" +
	"\x06status\x18) \x01(\x05R\x06status\x12#\n" +
	"\rfinish_reason\x18* \x01(\tR\ffinishReason\x12\x1d\n" +
	"\n" +
	"error_code\x18+ \x01(\tR\terrorCode\x12\x1b\n" +
	"\tcache_hit\x18, \x01(\bR\bcacheHit\x12\x19\n" +
	"\bcost_usd\x182 \x01(\x01R\acostUsd\x12\x1f\n" +
	"\vworkflow_id\x18< \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\bagent_id\x18= \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18> \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18? \x01(\tR\x06userId\"\x86\x04\n" +
	"\rWorkflowEvent\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12,\n" +
	"\x12parent_workflow_id\x18\x03 \x01(\tR\x10parentWorkflowId\x12<\n" +
	"\x05state\x18\x04 \x01(\x0e2&.tokenops.eventschema.v1.WorkflowStateR\x05state\x12\x1d\n" +
	"\n" +
	"step_count\x18\n" +
	" \x01(\x03R\tstepCount\x126\n" +
	"\x17cumulative_input_tokens\x18\v \x01(\x03R\x15cumulativeInputTokens\x128\n" +
	"\x18cumulative_output_tokens\x18\f \x01(\x03R\x16cumulativeOutputTokens\x126\n" +
	"\x17cumulative_total_tokens\x18\r \x01(\x03R\x15cumulativeTotalTokens\x12.\n" +
	"\x13cumulative_cost_usd\x18\x0e \x01(\x01R\x11cumulativeCostUsd\x125\n" +
	"\bduration\x18\x14 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x1d\n" +
	"\n" +
	"error_code\x18\x1e \x01(\tR\terrorCode\"\x90\x04\n" +
	"\x11OptimizationEvent\x12\x1f\n" +
	"\vprompt_hash\x18\x01 \x01(\tR\n" +
	"promptHash\x12=\n" +
	"\x04type\x18\x02 \x01(\x0e2).tokenops.eventschema.v1.OptimizationTypeR\x04type\x12=\n" +
	"\x04mode\x18\x03 \x01(\x0e2).tokenops.eventschema.v1.OptimizationModeR\x04mode\x128\n" +
	"\x18estimated_savings_tokens\x18\n" +
	" \x01(\x03R\x16estimatedSavingsTokens\x122\n" +
	"\x15estimated_savings_usd\x18\v \x01(\x01R\x13estimatedSavingsUsd\x12#\n" +
	"\rquality_score\x18\f \x01(\x01R\fqualityScore\x12I\n" +
	"\bdecision\x18\x14 \x01(\x0e2-.tokenops.eventschema.v1.OptimizationDecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x15 \x01(\tR\x06reason\x12*\n" +
	"\x11latency_impact_ns\x18\x1e \x01(\x03R\x0flatencyImpactNs\x12\x1f\n" +
	"\vworkflow_id\x18( \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\bagent_id\x18) \x01(\tR\aagentId\"\x9e\x05\n" +
	"\rCoachingEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12G\n" +
	"\x04kind\x18\x04 \x01(\x0e23.tokenops.eventschema.v1.CoachingRecommendationKindR\x04kind\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\x128\n" +
	"\x18estimated_savings_tokens\x18\n" +
	" \x01(\x03R\x16estimatedSavingsTokens\x122\n" +
	"\x15estimated_savings_usd\x18\v \x01(\x01R\x13estimatedSavingsUsd\x12)\n" +
	"\x10efficiency_score\x18\x14 \x01(\x01R\x0fefficiencyScore\x12)\n" +
	"\x10efficiency_delta\x18\x15 \x01(\x01R\x0fefficiencyDelta\x12c\n" +
	"\x0freplay_metadata\x18\x1e \x03(\v2:.tokenops.eventschema.v1.CoachingEvent.ReplayMetadataEntryR\x0ereplayMetadata\x12I\n" +
	"\bdecision\x18\x1f \x01(\x0e2-.tokenops.eventschema.v1.OptimizationDecisionR\bdecision\x1aA\n" +
	"\x13ReplayMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd9\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_TYPE_PROMPT\x10\x01\x12\x17\n" +
	"\x13EVENT_TYPE_WORKFLOW\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_OPTIMIZATION\x10\x03\x12\x17\n" +
	"\x13EVENT_TYPE_COACHING\x10\x04\x12\x17\n" +
	"\x13EVENT_TYPE_DECISION\x10\a\x12\x16\n" +
	"\x12EVENT_TYPE_OUTCOME\x10\b\x12\x19\n" +
	"\x15EVENT_TYPE_EXPERIMENT\x10\t*f\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROVIDER_OPENAI\x10\x01\x12\x16\n" +
	"\x12PROVIDER_ANTHROPIC\x10\x02\x12\x13\n" +
	"\x0fPROVIDER_GEMINI\x10\x03*\xa1\x01\n" +
	"\rWorkflowState\x12\x1e\n" +
	"\x1aWORKFLOW_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKFLOW_STATE_STARTED\x10\x01\x12\x1b\n" +
	"\x17WORKFLOW_STATE_PROGRESS\x10\x02\x12\x1c\n" +
	"\x18WORKFLOW_STATE_COMPLETED\x10\x03\x12\x19\n" +
	"\x15WORKFLOW_STATE_FAILED\x10\x04*\xab\x02\n" +
	"\x10OptimizationType\x12!\n" +
	"\x1dOPTIMIZATION_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!OPTIMIZATION_TYPE_PROMPT_COMPRESS\x10\x01\x12\x1c\n" +
	"\x18OPTIMIZATION_TYPE_DEDUPE\x10\x02\x12%\n" +
	"!OPTIMIZATION_TYPE_RETRIEVAL_PRUNE\x10\x03\x12\"\n" +
	"\x1eOPTIMIZATION_TYPE_CONTEXT_TRIM\x10\x04\x12#\n" +
	"\x1fOPTIMIZATION_TYPE_SYSTEM_DEDUPE\x10\x05\x12\x1c\n" +
	"\x18OPTIMIZATION_TYPE_ROUTER\x10\x06\x12!\n" +
	"\x1dOPTIMIZATION_TYPE_CACHE_REUSE\x10\a*\x95\x01\n" +
	"\x10OptimizationMode\x12!\n" +
	"\x1dOPTIMIZATION_MODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19OPTIMIZATION_MODE_PASSIVE\x10\x01\x12!\n" +
	"\x1dOPTIMIZATION_MODE_INTERACTIVE\x10\x02\x12\x1c\n" +
	"\x18OPTIMIZATION_MODE_REPLAY\x10\x03*\xcb\x01\n" +
	"\x14OptimizationDecision\x12%\n" +
	"!OPTIMIZATION_DECISION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dOPTIMIZATION_DECISION_APPLIED\x10\x01\x12\"\n" +
	"\x1eOPTIMIZATION_DECISION_ACCEPTED\x10\x02\x12\"\n" +
	"\x1eOPTIMIZATION_DECISION_REJECTED\x10\x03\x12!\n" +
	"\x1dOPTIMIZATION_DECISION_SKIPPED\x10\x04*\xa9\x02\n" +
	"\x1aCoachingRecommendationKind\x12\x1d\n" +
	"\x19COACHING_KIND_UNSPECIFIED\x10\x00\x12$\n" +
	" COACHING_KIND_REDUCE_PROMPT_SIZE\x10\x01\x12\x1e\n" +
	"\x1aCOACHING_KIND_TRIM_CONTEXT\x10\x02\x12\"\n" +
	"\x1eCOACHING_KIND_SHRINK_RETRIEVAL\x10\x03\x12\x1d\n" +
	"\x19COACHING_KIND_REUSE_CACHE\x10\x04\x12\x1e\n" +
	"\x1aCOACHING_KIND_SWITCH_MODEL\x10\x05\x12 \n" +
	"\x1cCOACHING_KIND_BATCH_REQUESTS\x10\x06\x12!\n" +
	"\x1dCOACHING_KIND_BREAK_RECURSION\x10\aB@Z>go.klarlabs.de/tokenops/pkg/eventschema/proto/v1;eventschemav1b\x06proto3"

var (
	file_pkg_eventschema_proto_v1_events_proto_rawDescOnce sync.Once
	file_pkg_eventschema_proto_v1_events_proto_rawDescData []byte
)

func file_pkg_eventschema_proto_v1_events_proto_rawDescGZIP() []byte {
	file_pkg_eventschema_proto_v1_events_proto_rawDescOnce.Do(func() {
		file_pkg_eventschema_proto_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_eventschema_proto_v1_events_proto_rawDesc), len(file_pkg_eventschema_proto_v1_events_proto_rawDesc)))
	})
	return file_pkg_eventschema_proto_v1_events_proto_rawDescData
}

var file_pkg_eventschema_proto_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_pkg_eventschema_proto_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_eventschema_proto_v1_events_proto_goTypes = []any{
	(EventType)(0),                  // 0: tokenops.eventschema.v1.EventType
	(Provider)(0),                   // 1: tokenops.eventschema.v1.Provider
	(WorkflowState)(0),              // 2: tokenops.eventschema.v1.WorkflowState
	(OptimizationType)(0),           // 3: tokenops.eventschema.v1.OptimizationType
	(OptimizationMode)(0),           // 4: tokenops.eventschema.v1.OptimizationMode
	(OptimizationDecision)(0),       // 5: tokenops.eventschema.v1.OptimizationDecision
	(CoachingRecommendationKind)(0), // 6: tokenops.eventschema.v1.CoachingRecommendationKind
	(*Envelope)(nil),                // 7: tokenops.eventschema.v1.Envelope
	(*Correlation)(nil),             // 8: tokenops.eventschema.v1.Correlation
	(*ResourceOption)(nil),          // 9: tokenops.eventschema.v1.ResourceOption
	(*EvidenceRef)(nil),             // 10: tokenops.eventschema.v1.EvidenceRef
	(*DecisionEvent)(nil),           // 11: tokenops.eventschema.v1.DecisionEvent
	(*OutcomeMetric)(nil),           // 12: tokenops.eventschema.v1.OutcomeMetric
	(*OutcomeEvent)(nil),            // 13: tokenops.eventschema.v1.OutcomeEvent
	(*ExperimentEvent)(nil),         // 14: tokenops.eventschema.v1.ExperimentEvent
	(*PromptEvent)(nil),             // 15: tokenops.eventschema.v1.PromptEvent
	(*WorkflowEvent)(nil),           // 16: tokenops.eventschema.v1.WorkflowEvent
	(*OptimizationEvent)(nil),       // 17: tokenops.eventschema.v1.OptimizationEvent
	(*CoachingEvent)(nil),           // 18: tokenops.eventschema.v1.CoachingEvent
	nil,                             // 19: tokenops.eventschema.v1.Envelope.AttributesEntry
	nil,                             // 20: tokenops.eventschema.v1.CoachingEvent.ReplayMetadataEntry
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),     // 22: google.protobuf.Duration
}
var file_pkg_eventschema_proto_v1_events_proto_depIdxs = []int32{
	0,  // 0: tokenops.eventschema.v1.Envelope.type:type_name -> tokenops.eventschema.v1.EventType
	21, // 1: tokenops.eventschema.v1.Envelope.timestamp:type_name -> google.protobuf.Timestamp
	19, // 2: tokenops.eventschema.v1.Envelope.attributes:type_name -> tokenops.eventschema.v1.Envelope.AttributesEntry
	8,  // 3: tokenops.eventschema.v1.Envelope.correlation:type_name -> tokenops.eventschema.v1.Correlation
	15, // 4: tokenops.eventschema.v1.Envelope.prompt:type_name -> tokenops.eventschema.v1.PromptEvent
	16, // 5: tokenops.eventschema.v1.Envelope.workflow:type_name -> tokenops.eventschema.v1.WorkflowEvent
	17, // 6: tokenops.eventschema.v1.Envelope.optimization:type_name -> tokenops.eventschema.v1.OptimizationEvent
	18, // 7: tokenops.eventschema.v1.Envelope.coaching:type_name -> tokenops.eventschema.v1.CoachingEvent
	11, // 8: tokenops.eventschema.v1.Envelope.decision:type_name -> tokenops.eventschema.v1.DecisionEvent
	13, // 9: tokenops.eventschema.v1.Envelope.outcome:type_name -> tokenops.eventschema.v1.OutcomeEvent
	14, // 10: tokenops.eventschema.v1.Envelope.experiment:type_name -> tokenops.eventschema.v1.ExperimentEvent
	21, // 11: tokenops.eventschema.v1.EvidenceRef.observed_at:type_name -> google.protobuf.Timestamp
	21, // 12: tokenops.eventschema.v1.EvidenceRef.fresh_until:type_name -> google.protobuf.Timestamp
	9,  // 13: tokenops.eventschema.v1.DecisionEvent.alternatives:type_name -> tokenops.eventschema.v1.ResourceOption
	9,  // 14: tokenops.eventschema.v1.DecisionEvent.selected:type_name -> tokenops.eventschema.v1.ResourceOption
	10, // 15: tokenops.eventschema.v1.DecisionEvent.evidence:type_name -> tokenops.eventschema.v1.EvidenceRef
	21, // 16: tokenops.eventschema.v1.OutcomeMetric.observed_at:type_name -> google.protobuf.Timestamp
	10, // 17: tokenops.eventschema.v1.OutcomeEvent.evidence:type_name -> tokenops.eventschema.v1.EvidenceRef
	12, // 18: tokenops.eventschema.v1.OutcomeEvent.metrics:type_name -> tokenops.eventschema.v1.OutcomeMetric
	9,  // 19: tokenops.eventschema.v1.ExperimentEvent.baseline:type_name -> tokenops.eventschema.v1.ResourceOption
	9,  // 20: tokenops.eventschema.v1.ExperimentEvent.variant:type_name -> tokenops.eventschema.v1.ResourceOption
	21, // 21: tokenops.eventschema.v1.ExperimentEvent.ends_at:type_name -> google.protobuf.Timestamp
	1,  // 22: tokenops.eventschema.v1.PromptEvent.provider:type_name -> tokenops.eventschema.v1.Provider
	22, // 23: tokenops.eventschema.v1.PromptEvent.latency:type_name -> google.protobuf.Duration
	22, // 24: tokenops.eventschema.v1.PromptEvent.time_to_first_token:type_name -> google.protobuf.Duration
	2,  // 25: tokenops.eventschema.v1.WorkflowEvent.state:type_name -> tokenops.eventschema.v1.WorkflowState
	22, // 26: tokenops.eventschema.v1.WorkflowEvent.duration:type_name -> google.protobuf.Duration
	3,  // 27: tokenops.eventschema.v1.OptimizationEvent.type:type_name -> tokenops.eventschema.v1.OptimizationType
	4,  // 28: tokenops.eventschema.v1.OptimizationEvent.mode:type_name -> tokenops.eventschema.v1.OptimizationMode
	5,  // 29: tokenops.eventschema.v1.OptimizationEvent.decision:type_name -> tokenops.eventschema.v1.OptimizationDecision
	6,  // 30: tokenops.eventschema.v1.CoachingEvent.kind:type_name -> tokenops.eventschema.v1.CoachingRecommendationKind
	20, // 31: tokenops.eventschema.v1.CoachingEvent.replay_metadata:type_name -> tokenops.eventschema.v1.CoachingEvent.ReplayMetadataEntry
	5,  // 32: tokenops.eventschema.v1.CoachingEvent.decision:type_name -> tokenops.eventschema.v1.OptimizationDecision
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_pkg_eventschema_proto_v1_events_proto_init() }
func file_pkg_eventschema_proto_v1_events_proto_init() {
	if File_pkg_eventschema_proto_v1_events_proto != nil {
		return
	}
	file_pkg_eventschema_proto_v1_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Prompt)(nil),
		(*Envelope_Workflow)(nil),
		(*Envelope_Optimization)(nil),
		(*Envelope_Coaching)(nil),
		(*Envelope_Decision)(nil),
		(*Envelope_Outcome)(nil),
		(*Envelope_Experiment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_eventschema_proto_v1_events_proto_rawDesc), len(file_pkg_eventschema_proto_v1_events_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_eventschema_proto_v1_events_proto_goTypes,
		DependencyIndexes: file_pkg_eventschema_proto_v1_events_proto_depIdxs,
		EnumInfos:         file_pkg_eventschema_proto_v1_events_proto_enumTypes,
		MessageInfos:      file_pkg_eventschema_proto_v1_events_proto_msgTypes,
	}.Build()
	File_pkg_eventschema_proto_v1_events_proto = out.File
	file_pkg_eventschema_proto_v1_events_proto_goTypes = nil
	file_pkg_eventschema_proto_v1_events_proto_depIdxs = nil
}
