package opencodeplugin

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// oldV1 is a plugin as tokenops wrote it before one file served both
// opencode generations: a named export, which opencode 2 refuses with
// "Plugin must export a default definition with an id and an effect or
// setup function." on every start.
const oldV1 = `// Generated by tokenops v0.97.0 — do not edit.
const TOKENOPS = "/opt/homebrew/bin/tokenops"

async function run(args, payload) { return null }

export const Tokenops = async ({ client }) => ({
  event: async ({ event }) => {
    const out = await run(["coach-hook", "--budget", "42"], {})
  },
})
`

const oldV2 = `// Generated by tokenops v0.97.0 for opencode 2 — do not edit.
const TOKENOPS = "/opt/homebrew/bin/tokenops"

export default {
  id: "tokenops",
  async setup(ctx) {
    await ctx.tool.hook("execute.before", async (event) => {
      const out = await run(["read-guard"], {})
    })
  },
}
`

func TestRenderServesEveryOpencodeVersion(t *testing.T) {
	body := Render(Plugin{Exe: "/bin/tokenops", ReadGuard: true, Coach: true, RouteGuard: true, Budget: 50}, "v1.0.0")
	for _, want := range []string{
		`export default {`, `id: "tokenops"`,
		`server: async ({ client }) => ({`, `"tool.execute.before": async (input, output)`,
		`"chat.message"`, `event: async ({ event })`,
		`async setup(ctx) {`, `ctx.tool.hook("execute.before"`, `args.path ?? args.filePath`,
		`ctx.session.hook("prompt"`, `throw new Error(denyReason)`,
		`const TOKENOPS = "/bin/tokenops"`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("plugin lacks %q", want)
		}
	}
	// opencode 1.x's fallback loader runs every export; a named one next to
	// the default would install the hooks twice.
	if strings.Contains(body, "export const") {
		t.Error("a named export would be loaded as a second plugin by opencode 1.x")
	}
	if strings.Count(body, `run(["coach-hook"`) != 1 {
		t.Error("opencode 2 has no channel for a nudge; the coach half is 1.x only")
	}
	checkSyntax(t, body)
}

func TestRenderWithOneHalfIsStillValid(t *testing.T) {
	for _, p := range []Plugin{
		{Exe: "/bin/tokenops", Coach: true, Budget: 10},
		{Exe: "/bin/tokenops", ReadGuard: true},
		{Exe: "/bin/tokenops", RouteGuard: true},
	} {
		checkSyntax(t, Render(p, "v1.0.0"))
	}
}

func TestParseReadsBackWhatRenderWrote(t *testing.T) {
	want := Plugin{Exe: "/x/tokenops", ReadGuard: true, Coach: true, Budget: 12.5}
	if got := Parse(Render(want, "v1"), 50); got != want {
		t.Errorf("got %+v, want %+v", got, want)
	}
}

func TestRefreshRewritesAnOlderPluginKeepingWhatItDid(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, FileName, oldV1)
	res, err := Refresh(dir, "v1.0.0", 50)
	if err != nil {
		t.Fatal(err)
	}
	if !res.Rewritten {
		t.Fatal("an older plugin was not rewritten")
	}
	got := Parse(read(t, dir, FileName), 50)
	want := Plugin{Exe: "/opt/homebrew/bin/tokenops", Coach: true, Budget: 42}
	if got != want {
		t.Errorf("got %+v, want %+v", got, want)
	}
	again, err := Refresh(dir, "v1.0.0", 50)
	if err != nil || again.Rewritten {
		t.Errorf("a current plugin was rewritten again: %+v %v", again, err)
	}
}

func TestRefreshFoldsTheLegacyV2PluginIn(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, FileName, oldV1)
	write(t, dir, LegacyV2FileName, oldV2)
	res, err := Refresh(dir, "v1.0.0", 50)
	if err != nil {
		t.Fatal(err)
	}
	if !res.RemovedLegacy {
		t.Error("legacy file not removed")
	}
	if _, err := os.Stat(filepath.Join(dir, LegacyV2FileName)); !os.IsNotExist(err) {
		t.Error("legacy file still on disk")
	}
	got := Parse(read(t, dir, FileName), 50)
	if !got.ReadGuard || !got.Coach || got.Budget != 42 {
		t.Errorf("merged plugin lost a half: %+v", got)
	}
}

// Someone on opencode 2 alone had only the legacy file.
func TestRefreshMovesALoneLegacyPlugin(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, LegacyV2FileName, oldV2)
	if _, err := Refresh(dir, "v1.0.0", 50); err != nil {
		t.Fatal(err)
	}
	got := Parse(read(t, dir, FileName), 50)
	if !got.ReadGuard || got.Exe != "/opt/homebrew/bin/tokenops" {
		t.Errorf("got %+v", got)
	}
}

func TestRefreshNeverTouchesWhatTokenopsDidNotWrite(t *testing.T) {
	dir := t.TempDir()
	mine := "export default { id: \"mine\", async setup() {} }\n"
	write(t, dir, FileName, mine)
	write(t, dir, LegacyV2FileName, mine)
	res, err := Refresh(dir, "v1.0.0", 50)
	if err != nil {
		t.Fatal(err)
	}
	if res.Rewritten || res.RemovedLegacy || read(t, dir, FileName) != mine || read(t, dir, LegacyV2FileName) != mine {
		t.Errorf("foreign plugins changed: %+v", res)
	}
}

// Refresh repairs an install; it never creates one.
func TestRefreshCreatesNothing(t *testing.T) {
	dir := t.TempDir()
	if _, err := Refresh(dir, "v1.0.0", 50); err != nil {
		t.Fatal(err)
	}
	if _, err := Refresh(filepath.Join(dir, "missing"), "v1.0.0", 50); err != nil {
		t.Fatal(err)
	}
	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Errorf("refresh created %d file(s)", len(entries))
	}
}

func checkSyntax(t *testing.T, body string) {
	t.Helper()
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node not installed; syntax not checked")
	}
	path := filepath.Join(t.TempDir(), "plugin.mjs")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	if out, err := exec.Command(node, "--check", path).CombinedOutput(); err != nil { //nolint:gosec // test-only
		t.Fatalf("generated plugin is not valid JavaScript: %v\n%s\n%s", err, out, body)
	}
}

func write(t *testing.T, dir, name, body string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

func read(t *testing.T, dir, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, name)) //nolint:gosec // test temp dir
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}
