// Package opencodeplugin generates the opencode plugin TokenOps installs.
//
// opencode is the only client besides Claude Code where read-guard can
// actually refuse a read. Codex has no file-read tool at all, and Cursor's
// beforeReadFile is observe-only — both are recorded as permanently
// unavailable in the capability matrix. opencode has a `read` tool and a
// `tool.execute.before` hook that blocks when it throws.
//
// What it does not have is a config file we can merge into: its extension
// point is a JavaScript module. So this generates one.
//
// Generating rather than shipping is the whole design. A published package
// would mean a second artifact, a second release path, and a version skew
// between the plugin and the binary it calls. A generated file has none of
// that: it is written by the binary, names the version that wrote it,
// hardcodes the absolute path to that same binary, and is rewritten in
// place by the next install — or by the daemon when it starts on a newer
// binary (Refresh).
//
// One file serves every opencode generation. Its default export carries
// an id, a `server` function (opencode 1.x calls it for a hooks object)
// and a `setup` function (opencode 2 calls it with a context to register
// hooks on). Each version reads the half it knows and ignores the other —
// verified on opencode 1.18.32 and 2.0.24. There is deliberately no named
// export: opencode 1.x's fallback loader would run it as a second plugin.
//
// It used to be two files, one per version, each "skipped with a logged
// load error" by the other version. opencode 2 shows that load error as a
// dialog on every start, so the 1.x file was an error in every 2.x
// session.
package opencodeplugin

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// FileName is the generated plugin. Named for tokenops so a human reading
// their plugin directory knows what wrote it and what to delete.
const FileName = "tokenops-read-guard.ts"

// LegacyV2FileName is the separate opencode 2 plugin earlier versions
// wrote. Its hooks now live in FileName, and both carry the id "tokenops",
// so it is folded in and removed.
const LegacyV2FileName = "tokenops-v2.js"

// generatedPrefix opens every file this package writes. A file without it
// was not written by TokenOps and is never rewritten.
const generatedPrefix = "// Generated by tokenops "

// Plugin is what a generated file does: which halves are wired, which
// binary they call, and the coach's budget.
type Plugin struct {
	Exe        string
	ReadGuard  bool
	Coach      bool
	RouteGuard bool
	// Budget is baked into the coach call; it matters only with Coach.
	Budget float64
}

// Empty reports whether no half is wired.
func (p Plugin) Empty() bool { return !p.ReadGuard && !p.Coach && !p.RouteGuard }

// Has reports whether the generated source still calls the given verb.
//
// Each generated body invokes the binary by name, so the call site is the
// marker and no JavaScript has to be parsed. It also means a file an
// operator hand-edited is read for what it actually does rather than for
// what we assume we wrote.
func Has(src, verb string) bool {
	return strings.Contains(src, `run(["`+verb+`"`)
}

// Exe recovers the binary path the plugin calls, so a rewrite keeps
// pointing at whatever the install pinned.
func Exe(src string) string {
	_, rest, ok := strings.Cut(src, "const TOKENOPS = ")
	if !ok {
		return ""
	}
	line, _, _ := strings.Cut(rest, "\n")
	path, err := strconv.Unquote(strings.TrimSpace(line))
	if err != nil {
		return ""
	}
	return path
}

// Budget recovers the budget baked into the coach call.
//
// A rewrite that regenerated with the default would silently move an
// operator's configured budget back to the default as a side effect of
// removing an unrelated guard.
func Budget(src string) (float64, bool) {
	_, rest, ok := strings.Cut(src, `run(["coach-hook", "--budget", "`)
	if !ok {
		return 0, false
	}
	value, _, ok := strings.Cut(rest, `"`)
	if !ok {
		return 0, false
	}
	v, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return 0, false
	}
	return v, true
}

// Generated reports whether src was written by TokenOps.
func Generated(src string) bool { return strings.HasPrefix(src, generatedPrefix) }

// Parse reads what a generated file does. defaultBudget stands in when the
// coach half is wired but its budget cannot be read back.
func Parse(src string, defaultBudget float64) Plugin {
	p := Plugin{
		Exe:        Exe(src),
		ReadGuard:  Has(src, "read-guard"),
		Coach:      Has(src, "coach-hook"),
		RouteGuard: Has(src, "route-guard"),
	}
	if p.Coach {
		if b, ok := Budget(src); ok {
			p.Budget = b
		} else {
			p.Budget = defaultBudget
		}
	}
	return p
}

// RefreshResult says what Refresh did.
type RefreshResult struct {
	// Rewritten is set when FileName was (re)written.
	Rewritten bool
	// RemovedLegacy is set when LegacyV2FileName was folded in and removed.
	RemovedLegacy bool
}

// Refresh rewrites a generated plugin in dir that an older TokenOps wrote,
// keeping its halves, binary and budget, and folds a legacy opencode 2
// file into it. Files TokenOps did not write are left alone, and a
// directory with no generated plugin is not touched: Refresh repairs an
// install, it never creates one.
func Refresh(dir, version string, defaultBudget float64) (RefreshResult, error) {
	var res RefreshResult
	path := filepath.Join(dir, FileName)
	legacyPath := filepath.Join(dir, LegacyV2FileName)
	current, haveCurrent, err := readGenerated(path)
	if err != nil {
		return res, err
	}
	legacy, haveLegacy, err := readGenerated(legacyPath)
	if err != nil {
		return res, err
	}
	if !haveCurrent && !haveLegacy {
		return res, nil
	}
	merged := Plugin{}
	if haveCurrent {
		merged = Parse(current, defaultBudget)
	}
	if haveLegacy {
		old := Parse(legacy, defaultBudget)
		merged.ReadGuard = merged.ReadGuard || old.ReadGuard
		merged.RouteGuard = merged.RouteGuard || old.RouteGuard
		if merged.Exe == "" {
			merged.Exe = old.Exe
		}
	}
	if merged.Empty() || merged.Exe == "" {
		// Nothing wired, or no binary to call: there is nothing a rewrite
		// could preserve, and guessing a binary would be inventing an install.
		return res, nil
	}
	body := Render(merged, version)
	if !haveCurrent || current != body {
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil { //nolint:gosec // the plugin the operator installed
			return res, fmt.Errorf("write %s: %w", path, err)
		}
		res.Rewritten = true
	}
	if haveLegacy {
		if err := os.Remove(legacyPath); err != nil {
			return res, fmt.Errorf("remove %s: %w", legacyPath, err)
		}
		res.RemovedLegacy = true
	}
	return res, nil
}

// RemoveLegacy deletes the separate opencode 2 plugin when TokenOps wrote
// it. Installing the combined file makes it a duplicate: both carry the id
// "tokenops".
func RemoveLegacy(dir string) (bool, error) {
	path := filepath.Join(dir, LegacyV2FileName)
	_, ok, err := readGenerated(path)
	if err != nil || !ok {
		return false, err
	}
	if err := os.Remove(path); err != nil {
		return false, fmt.Errorf("remove %s: %w", path, err)
	}
	return true, nil
}

// ReadLegacy returns the legacy opencode 2 plugin TokenOps wrote, if any.
func ReadLegacy(dir string) (string, bool, error) {
	return readGenerated(filepath.Join(dir, LegacyV2FileName))
}

// readGenerated reads path when it exists and TokenOps wrote it.
func readGenerated(path string) (string, bool, error) {
	b, err := os.ReadFile(path) //nolint:gosec // a plugin path under the opencode config dir
	if errors.Is(err, os.ErrNotExist) {
		return "", false, nil
	}
	if err != nil {
		return "", false, fmt.Errorf("read %s: %w", path, err)
	}
	src := string(b)
	return src, Generated(src), nil
}

// Render is the plugin with the chosen halves.
func Render(p Plugin, version string) string {
	v1 := readGuardV1(p.ReadGuard) + coachV1(p.Coach, p.Budget) + routeV1(p.RouteGuard)
	v2 := readGuardV2(p.ReadGuard) + routeV2(p.RouteGuard)
	return fmt.Sprintf(template, version, p.Exe, v1, v2)
}

// template is the shim. The first %s is the version, %q the binary, then
// the 1.x hooks object's members and the 2.x setup body.
//
// Three properties it must have, in order of how badly each would hurt:
//
//   - It FAILS OPEN. A guard sitting in front of every file read must
//     never be the reason an agent cannot read a file. Anything
//     unexpected — the binary missing, a spawn failure, unparseable
//     output — allows the read. Only an explicit deny throws, and the
//     throw happens outside the try so a bug in the error handling
//     cannot swallow a real refusal.
//   - It omits offset and limit rather than sending null. read-guard
//     treats the mere presence of either as a ranged read and always
//     allows those, so a literal null would disable the guard entirely
//     while appearing to work.
//   - It says nothing on allow. read-guard exits 0 with empty stdout for
//     a read it permits, which is the common case and must stay silent.
const template = `// Generated by tokenops %s — do not edit.
//
// Regenerate with:
//   tokenops hooks install --read-guard --coach --route-guard --client opencode
//
// Delete this file to remove it. Decisions are made by the tokenops
// binary below, which follows coaching.delivery in your tokenops config.
// One file for every opencode version: 1.x calls server(), opencode 2
// calls setup().
const TOKENOPS = %q

// run pipes a payload to the tokenops binary and returns its stdout,
// or null if anything at all went wrong. Everything here fails open:
// a coaching tool must never be the reason an agent cannot work.
async function run(args, payload) {
  try {
    const proc = Bun.spawn([TOKENOPS, ...args], {
      stdin: new TextEncoder().encode(JSON.stringify(payload)),
      stdout: "pipe",
      stderr: "ignore",
    })
    const out = (await new Response(proc.stdout).text()).trim()
    return out || null
  } catch {
    return null
  }
}

export default {
  id: "tokenops",
  // opencode 1.x
  server: async ({ client }) => ({
%s  }),
  // opencode 2
  async setup(ctx) {
%s  },
}
`

// readGuardV1 refuses a redundant full re-read of an unchanged file.
func readGuardV1(on bool) string {
	if !on {
		return ""
	}
	return `    "tool.execute.before": async (input, output) => {
      if (input?.tool !== "read") return
      const filePath = output?.args?.filePath
      if (!filePath) return
      let denyReason = null
      try {
        const toolInput = { file_path: filePath }
        if (output.args.offset !== undefined && output.args.offset !== null) {
          toolInput.offset = output.args.offset
        }
        if (output.args.limit !== undefined && output.args.limit !== null) {
          toolInput.limit = output.args.limit
        }
        const out = await run(["read-guard"], {
          session_id: input.sessionID ?? "",
          tool_name: "Read",
          tool_input: toolInput,
        })
        if (out) {
          const d = JSON.parse(out)?.hookSpecificOutput
          if (d?.permissionDecision === "deny") {
            denyReason = d.permissionDecisionReason || "tokenops read-guard: redundant re-read"
          }
        }
      } catch {
        // fail open
      }
      if (denyReason) throw new Error(denyReason)
    },
`
}

// coachV1 is the coaching half. opencode 1.x has no end-of-turn hook that
// takes a return value, so the nudge is delivered as a TUI toast — the one
// channel a plugin has to reach the operator. opencode 2 shows nudges in
// a TUI a server plugin cannot drive, so there is no 2.x counterpart.
//
// It carries no tokens in the event and no transcript path: the turns live
// in opencode's own store, which the binary reads by session id.
func coachV1(on bool, budget float64) string {
	if !on {
		return ""
	}
	return `    event: async ({ event }) => {
      if (event?.type !== "session.idle") return
      const sessionID = event?.properties?.sessionID ?? event?.properties?.info?.id
      if (!sessionID) return
      try {
        const out = await run(["coach-hook", "--budget", "` + strconv.FormatFloat(budget, 'f', -1, 64) + `"], {
          session_id: sessionID,
          hook_event_name: "session.idle",
        })
        if (!out) return
        const msg = JSON.parse(out)?.systemMessage
        if (msg) {
          await client.tui.showToast({ body: { title: "tokenops", message: msg, variant: "warning" } })
        }
      } catch {
        // fail open: a nudge that cannot be delivered is not worth an error
      }
    },
`
}

// routeV1 is the per-turn model-fit half. chat.message names the provider
// and the model outright; the advice is appended to the message parts, the
// only channel a plugin has into the turn the operator just opened.
func routeV1(on bool) string {
	if !on {
		return ""
	}
	return `    "chat.message": async (input, output) => {
      try {
        const text = (output?.parts ?? [])
          .filter((p) => p?.type === "text")
          .map((p) => p.text)
          .join(" ")
        if (!text.trim()) return
        const out = await run(["route-guard"], {
          session_id: input?.sessionID ?? "",
          prompt: text,
          provider_id: input?.model?.providerID ?? "",
          model_id: input?.model?.modelID ?? "",
        })
        if (!out) return
        const advice = JSON.parse(out)?.hookSpecificOutput?.additionalContext
        if (advice) {
          output.parts.push({ type: "text", text: advice })
        }
      } catch {
        // fail open: a turn must never fail because the guard could not decide
      }
    },
`
}

// readGuardV2 is read-guard for opencode 2, which names the file "path" (a
// 1.x call migrated to 2.x keeps "filePath"). A read from the start
// (offset 0 or 1) with no limit is a full read; any limit or later offset
// is a ranged read, which read-guard always allows.
func readGuardV2(on bool) string {
	if !on {
		return ""
	}
	return `    await ctx.tool.hook("execute.before", async (event) => {
      if (event?.tool !== "read") return
      const args = event.input ?? {}
      const filePath = args.path ?? args.filePath
      if (!filePath) return
      let denyReason = null
      try {
        const toolInput = { file_path: filePath }
        if (typeof args.offset === "number" && args.offset > 1) toolInput.offset = args.offset
        if (args.limit !== undefined && args.limit !== null) toolInput.limit = args.limit
        const out = await run(["read-guard"], {
          session_id: event.sessionID ?? "",
          tool_name: "Read",
          tool_input: toolInput,
        })
        if (out) {
          const d = JSON.parse(out)?.hookSpecificOutput
          if (d?.permissionDecision === "deny") {
            denyReason = d.permissionDecisionReason || "tokenops read-guard: redundant re-read"
          }
        }
      } catch {
        // fail open
      }
      if (denyReason) throw new Error(denyReason)
    })
`
}

// routeV2 checks the model still fits the work. The 2.x prompt hook
// carries the text but not the model, so the session is looked up for it;
// the advice is appended to the prompt the operator just submitted.
func routeV2(on bool) string {
	if !on {
		return ""
	}
	return `    await ctx.session.hook("prompt", async (event) => {
      try {
        const text = event?.prompt?.text ?? ""
        if (!text.trim()) return
        let model = {}
        try {
          const session = await ctx.session.get({ sessionID: event.sessionID })
          model = session?.model ?? {}
        } catch {
          // no model: route-guard still reads the work
        }
        const out = await run(["route-guard"], {
          session_id: event.sessionID ?? "",
          prompt: text,
          provider_id: model.providerID ?? "",
          model_id: model.id ?? "",
        })
        if (!out) return
        const advice = JSON.parse(out)?.hookSpecificOutput?.additionalContext
        if (advice) event.prompt.text = text + "\n\n" + advice
      } catch {
        // fail open: a turn must never fail because the guard could not decide
      }
    })
`
}

// Events names the extension point each verb hooks, per opencode version.
var Events = map[string]string{
	"read-guard":  "tool.execute.before",
	"coach-hook":  "session.idle (opencode 1.x)",
	"route-guard": "chat.message / session prompt",
}
