// Code generated by internal/tools/gen/listgen; DO NOT EDIT.

package accounts

import (
	usage "go.klarlabs.de/tokenops/internal/contexts/spend/vendorusage/accounts"
)

// readers is every reader*() function in this package, by file name.
var readers = []func() usage.Reader{
	readerAmpCLI,
	readerAmp,
	readerAugmentCLI,
	readerAugment,
	readerChutes,
	readerClinePass,
	readerCodebuff,
	readerDeepInfra,
	readerDeepSeek,
	readerDevPass,
	readerGitKraken,
	readerIBMBob,
	readerJetBrains,
	readerKilo,
	readerKimi,
	readerKiro,
	readerMiniMax,
	readerMoonshot,
	readerNous,
	readerOpenRouter,
	readerSynthetic,
	readerV0,
	readerVercel,
	readerWarp,
	readerWindsurfLocal,
	readerWindsurf,
	readerXKiro,
	readerZAI,
	readerZenMux,
}

// gateways is every gateway*() function in this package, by file name.
var gateways = []func() usage.Gateway{
	gatewayBifrost,
	gatewayClawRouter,
	gatewayLiteLLM,
}
