// Code generated by internal/tools/gen/listgen; DO NOT EDIT.

package accounts

import (
	usage "go.klarlabs.de/tokenops/internal/contexts/spend/vendorusage/accounts"
)

// readers is every reader*() function in this package, by file name.
var readers = []func() usage.Reader{
	readerAiAnd,
	readerAtlasCloud,
	readerChutes,
	readerClinePass,
	readerCodebuff,
	readerDeepgram,
	readerDeepInfra,
	readerDeepSeek,
	readerDevPass,
	readerDoubao,
	readerElevenLabs,
	readerHuggingFace,
	readerIBMBob,
	readerKilo,
	readerKimi,
	readerMiniMax,
	readerMoonshot,
	readerNeuralWatt,
	readerNous,
	readerOpenAIAdmin,
	readerOpencodeGo,
	readerOpenRouter,
	readerPoe,
	readerSynthetic,
	readerV0,
	readerVenice,
	readerVercel,
	readerWarp,
	readerXAI,
	readerXKiro,
	readerZAI,
	readerZenMux,
}

// gateways is every gateway*() function in this package, by file name.
var gateways = []func() usage.Gateway{
	gatewayAixy,
	gatewayBifrost,
	gatewayClawRouter,
	gatewayLiteLLM,
	gatewayLLMProxy,
	gatewaySub2API,
}
