// Code generated by internal/tools/gen/listgen; DO NOT EDIT.

package providers

// registered is every provider*() function in this package, by file name.
var registered = []func() Descriptor{
	providerAlibaba,
	providerAnthropic,
	providerBifrost,
	providerCerebras,
	providerChutes,
	providerClawRouter,
	providerClinePass,
	providerCursor,
	providerDeepInfra,
	providerDeepSeek,
	providerFireworks,
	providerGemini,
	providerGitHub,
	providerKimi,
	providerLiteLLM,
	providerMiniMax,
	providerMistral,
	providerMoonshot,
	providerOpenAI,
	providerOpencode,
	providerOpencodeGo,
	providerOpenRouter,
	providerSynthetic,
	providerTogether,
	providerVercel,
	providerXAI,
	providerZAI,
	providerZhipuAI,
}
